// Auto-generated communes data for Algeria (wilayas 1-58)
// Source: S450R1/algeria-cities-2025

export interface SeedCommune {
  nameAr: string;
  nameFr: string;
}

export const SEED_COMMUNES: Record<number, SeedCommune[]> = {
  1: [
    { nameAr: 'تيمقتن', nameFr: 'Timekten' },
    { nameAr: 'بودة', nameFr: 'Bouda' },
    { nameAr: 'أولاد أحمد تيمي', nameFr: 'Ouled Ahmed Timmi' },
    { nameAr: 'أدرار', nameFr: 'Adrar' },
    { nameAr: 'فنوغيل', nameFr: 'Fenoughil' },
    { nameAr: 'إن زغمير', nameFr: 'In Zghmir' },
    { nameAr: 'رقان', nameFr: 'Reggane' },
    { nameAr: 'سالي', nameFr: 'Sali' },
    { nameAr: 'السبع', nameFr: 'Sebaa' },
    { nameAr: 'تسابيت', nameFr: 'Tsabit' },
    { nameAr: 'تامست', nameFr: 'Tamest' },
    { nameAr: 'تامنطيط', nameFr: 'Tamantit' },
    { nameAr: 'تيت', nameFr: 'Tit' },
    { nameAr: 'زاوية كنتة', nameFr: 'Zaouiet Kounta' },
    { nameAr: 'اقبلي', nameFr: 'Akabli' },
    { nameAr: 'أولف', nameFr: 'Aoulef' },
  ],
  2: [
    { nameAr: 'تلعصة', nameFr: 'Talassa' },
    { nameAr: 'الزبوجة', nameFr: 'Zeboudja' },
    { nameAr: 'الحجاج', nameFr: 'El Hadjadj' },
    { nameAr: 'أولاد بن عبد القادر', nameFr: 'Ouled Ben Abdelkader' },
    { nameAr: 'عين مران', nameFr: 'Ain Merane' },
    { nameAr: 'بريرة', nameFr: 'Breira' },
    { nameAr: 'أولاد عباس', nameFr: 'Ouled Abbes' },
    { nameAr: 'وادي الفضة', nameFr: 'Oued Fodda' },
    { nameAr: 'بني راشد', nameFr: 'Beni Rached' },
    { nameAr: 'الهرانفة', nameFr: 'Herenfa' },
    { nameAr: 'تاجنة', nameFr: 'Tadjena' },
    { nameAr: 'المرسى', nameFr: 'El Marsa' },
    { nameAr: 'الشلف', nameFr: 'Chlef' },
    { nameAr: 'أم الدروع', nameFr: 'Oum Drou' },
    { nameAr: 'سنجاس', nameFr: 'Sendjas' },
    { nameAr: 'سيدي عبد الرحمن', nameFr: 'Sidi Abderrahmane' },
    { nameAr: 'سيدي عكاشة', nameFr: 'Sidi Akkacha' },
    { nameAr: 'تنس', nameFr: 'Tenes' },
    { nameAr: 'بني بوعتاب', nameFr: 'Beni  Bouattab' },
    { nameAr: 'الكريمية', nameFr: 'El Karimia' },
    { nameAr: 'حرشون', nameFr: 'Harchoun' },
    { nameAr: 'بوزغاية', nameFr: 'Bouzeghaia' },
    { nameAr: 'تاوقريت', nameFr: 'Taougrit' },
    { nameAr: 'بني حواء', nameFr: 'Beni Haoua' },
    { nameAr: 'أبو الحسن', nameFr: 'Abou El Hassane' },
    { nameAr: 'وادي قوسين', nameFr: 'Oued Goussine' },
    { nameAr: 'الشطية', nameFr: 'Chettia' },
    { nameAr: 'مصدق', nameFr: 'Moussadek' },
    { nameAr: 'أولاد فارس', nameFr: 'Ouled Fares' },
    { nameAr: 'بوقادير', nameFr: 'Boukadir' },
    { nameAr: 'وادي سلي', nameFr: 'Oued Sly' },
    { nameAr: 'الصبحة', nameFr: 'Sobha' },
    { nameAr: 'بنايرية', nameFr: 'Benairia' },
    { nameAr: 'الأبيض مجاجة', nameFr: 'Labiod Medjadja' },
    { nameAr: 'الظهرة', nameFr: 'Dahra' },
  ],
  3: [
    { nameAr: 'تاجموت', nameFr: 'Tadjemout' },
    { nameAr: 'تاجرونة', nameFr: 'Tadjrouna' },
    { nameAr: 'الأغواط', nameFr: 'Laghouat' },
    { nameAr: 'قصر الحيران', nameFr: 'Ksar El Hirane' },
    { nameAr: 'العسافية', nameFr: 'El Assafia' },
    { nameAr: 'سيدي مخلوف', nameFr: 'Sidi Makhlouf' },
    { nameAr: 'حاسي الدلاعة', nameFr: 'Hassi Delaa' },
    { nameAr: 'حاسي الرمل', nameFr: 'Hassi R\'mel' },
    { nameAr: 'عين ماضي', nameFr: 'Ain Madhi' },
    { nameAr: 'الحويطة', nameFr: 'El Haouaita' },
    { nameAr: 'الخنق', nameFr: 'Kheneg' },
    { nameAr: 'بن ناصر بن شهرة', nameFr: 'Benacer Benchohra' },
  ],
  4: [
    { nameAr: 'فكيرينة', nameFr: 'Fkirina' },
    { nameAr: 'الفجوج بوغرارة سعودي', nameFr: 'El Fedjoudj Boughrara Sa' },
    { nameAr: 'عين فكرون', nameFr: 'Ain Fekroun' },
    { nameAr: 'الرحية', nameFr: 'Rahia' },
    { nameAr: 'مسكيانة', nameFr: 'Meskiana' },
    { nameAr: 'البلالة', nameFr: 'El Belala' },
    { nameAr: 'بحير الشرقي', nameFr: 'Behir Chergui' },
    { nameAr: 'قصر الصباحي', nameFr: 'Ksar Sbahi' },
    { nameAr: 'سوق نعمان', nameFr: 'Souk Naamane' },
    { nameAr: 'أولاد زواي', nameFr: 'Ouled Zouai' },
    { nameAr: 'أم البواقي', nameFr: 'Oum El Bouaghi' },
    { nameAr: 'عين ببوش', nameFr: 'Ain Babouche' },
    { nameAr: 'عين الزيتون', nameFr: 'Ain Zitoun' },
    { nameAr: 'بئر الشهداء', nameFr: 'Bir Chouhada' },
    { nameAr: 'عين البيضاء', nameFr: 'Ain Beida' },
    { nameAr: 'بريش', nameFr: 'Berriche' },
    { nameAr: 'الزرق', nameFr: 'Zorg' },
    { nameAr: 'عين مليلة', nameFr: 'Ain M\'lila' },
    { nameAr: 'أولاد قاسم', nameFr: 'Ouled Gacem' },
    { nameAr: 'أولاد حملة', nameFr: 'Ouled Hamla' },
    { nameAr: 'العامرية', nameFr: 'El Amiria' },
    { nameAr: 'سيقوس', nameFr: 'Sigus' },
    { nameAr: 'وادي نيني', nameFr: 'Oued Nini' },
    { nameAr: 'عين الديس', nameFr: 'Ain Diss' },
    { nameAr: 'الضلعة', nameFr: 'Dhalaa' },
    { nameAr: 'الجازية', nameFr: 'El Djazia' },
    { nameAr: 'عين كرشة', nameFr: 'Ain Kercha' },
    { nameAr: 'الحرملية', nameFr: 'El Harmilia' },
    { nameAr: 'هنشير تومغني', nameFr: 'Hanchir Toumghani' },
  ],
  5: [
    { nameAr: 'معافة', nameFr: 'Maafa' },
    { nameAr: 'القصبات', nameFr: 'Gosbat' },
    { nameAr: 'تيمقاد', nameFr: 'Timgad' },
    { nameAr: 'تاكسلانت', nameFr: 'Taxlent' },
    { nameAr: 'أولاد سي سليمان', nameFr: 'Ouled Si Slimane' },
    { nameAr: 'لمسان', nameFr: 'Lemcene' },
    { nameAr: 'تالخمت', nameFr: 'Talkhamt' },
    { nameAr: 'رأس العيون', nameFr: 'Ras El Aioun' },
    { nameAr: 'الرحبات', nameFr: 'Rahbat' },
    { nameAr: 'أولاد سلام', nameFr: 'Ouled Sellem' },
    { nameAr: 'القيقبة', nameFr: 'Guigba' },
    { nameAr: 'ثنية العابد', nameFr: 'Teniet El Abed' },
    { nameAr: 'باتنة', nameFr: 'Batna' },
    { nameAr: 'فسديس', nameFr: 'Fesdis' },
    { nameAr: 'وادي الشعبة', nameFr: 'Oued Chaaba' },
    { nameAr: 'حيدوسة', nameFr: 'Hidoussa' },
    { nameAr: 'قصر بلزمة', nameFr: 'Ksar Bellezma' },
    { nameAr: 'مروانة', nameFr: 'Merouana' },
    { nameAr: 'وادي الماء', nameFr: 'Oued El Ma' },
    { nameAr: 'لازرو', nameFr: 'Lazrou' },
    { nameAr: 'سريانة', nameFr: 'Seriana' },
    { nameAr: 'زانة البيضاء', nameFr: 'Zanet El Beida' },
    { nameAr: 'منعة', nameFr: 'Menaa' },
    { nameAr: 'تغرغار', nameFr: 'Tigharghar' },
    { nameAr: 'عين ياقوت', nameFr: 'Ain Yagout' },
    { nameAr: 'بومية', nameFr: 'Boumia' },
    { nameAr: 'جرمة', nameFr: 'Djerma' },
    { nameAr: 'المعذر', nameFr: 'El Madher' },
    { nameAr: 'عيون العصافير', nameFr: 'Ouyoun El Assafir' },
    { nameAr: 'تازولت', nameFr: 'Tazoult' },
    { nameAr: 'بومقر', nameFr: 'Boumagueur' },
    { nameAr: 'نقاوس', nameFr: 'N Gaous' },
    { nameAr: 'سفيان', nameFr: 'Sefiane' },
    { nameAr: 'أريس', nameFr: 'Arris' },
    { nameAr: 'تيغانمين', nameFr: 'Tighanimine' },
    { nameAr: 'عين جاسر', nameFr: 'Ain Djasser' },
    { nameAr: 'الحاسي', nameFr: 'El Hassi' },
    { nameAr: 'فم الطوب', nameFr: 'Foum Toub' },
    { nameAr: 'إشمول', nameFr: 'Ichemoul' },
    { nameAr: 'إينوغيسن', nameFr: 'Inoughissen' },
    { nameAr: 'بوزينة', nameFr: 'Bouzina' },
    { nameAr: 'لارباع', nameFr: 'Larbaa' },
    { nameAr: 'بولهيلات', nameFr: 'Boulhilat' },
    { nameAr: 'الشمرة', nameFr: 'Chemora' },
    { nameAr: 'غسيرة', nameFr: 'Ghassira' },
    { nameAr: 'كيمل', nameFr: 'Kimmel' },
    { nameAr: 'تكوت', nameFr: 'T Kout' },
    { nameAr: 'عين التوتة', nameFr: 'Ain Touta' },
    { nameAr: 'بني فضالة الحقانية', nameFr: 'Beni Foudhala El Hakania' },
    { nameAr: 'أولاد فاضل', nameFr: 'Ouled Fadel' },
    { nameAr: 'أولاد عوف', nameFr: 'Ouled Aouf' },
    { nameAr: 'شير', nameFr: 'Chir' },
    { nameAr: 'وادي الطاقة', nameFr: 'Oued Taga' },
  ],
  6: [
    { nameAr: 'سيدي عياد', nameFr: 'Sidi Ayad' },
    { nameAr: 'برباشة', nameFr: 'Barbacha' },
    { nameAr: 'الفلاي', nameFr: 'Leflaye' },
    { nameAr: 'كنديرة', nameFr: 'Kendira' },
    { nameAr: 'سيدي عيش', nameFr: 'Sidi-Aich' },
    { nameAr: 'تيفرة', nameFr: 'Tifra' },
    { nameAr: 'تينبدار', nameFr: 'Tinebdar' },
    { nameAr: 'القصر', nameFr: 'El Kseur' },
    { nameAr: 'فناية الماثن', nameFr: 'Fenaia Il Maten' },
    { nameAr: 'توجة', nameFr: 'Toudja' },
    { nameAr: 'ذراع القايد', nameFr: 'Dra El Caid' },
    { nameAr: 'خراطة', nameFr: 'Kherrata' },
    { nameAr: 'بجاية', nameFr: 'Bejaia' },
    { nameAr: 'وادي غير', nameFr: 'Oued Ghir' },
    { nameAr: 'بني معوش', nameFr: 'Benimaouche' },
    { nameAr: 'بني جليل', nameFr: 'Beni Djellil' },
    { nameAr: 'فرعون', nameFr: 'Feraoun' },
    { nameAr: 'سمعون', nameFr: 'Smaoun' },
    { nameAr: 'تيمزريت', nameFr: 'Timezrit' },
    { nameAr: 'مالبو', nameFr: 'Melbou' },
    { nameAr: 'سوق لإثنين', nameFr: 'Souk El Tenine' },
    { nameAr: 'تامريجت', nameFr: 'Tamridjet' },
    { nameAr: 'بوخليفة', nameFr: 'Boukhelifa' },
    { nameAr: 'تالة حمزة', nameFr: 'Tala Hamza' },
    { nameAr: 'تيشي', nameFr: 'Tichy' },
    { nameAr: 'أيت رزين', nameFr: 'Ait R\'zine' },
    { nameAr: 'إغيل علي', nameFr: 'Ighil-Ali' },
    { nameAr: 'أيت إسماعيل', nameFr: 'Ait-Smail' },
    { nameAr: 'درقينة', nameFr: 'Darguina' },
    { nameAr: 'تاسكريوت', nameFr: 'Taskriout' },
    { nameAr: 'أوقاس', nameFr: 'Aokas' },
    { nameAr: 'تيزي نبربر', nameFr: 'Tizi-N\'berber' },
    { nameAr: 'أدكار', nameFr: 'Adekar' },
    { nameAr: 'بني كسيلة', nameFr: 'Beni K\'sila' },
    { nameAr: 'تاوريرت إغيل', nameFr: 'Taourit Ighil' },
    { nameAr: 'أقبو', nameFr: 'Akbou' },
    { nameAr: 'شلاطة', nameFr: 'Chellata' },
    { nameAr: 'اغرم', nameFr: 'Ighram' },
    { nameAr: 'تامقرة', nameFr: 'Tamokra' },
    { nameAr: 'أمالو', nameFr: 'Amalou' },
    { nameAr: 'بوحمزة', nameFr: 'Bouhamza' },
    { nameAr: 'مسيسنة', nameFr: 'M\'cisna' },
    { nameAr: 'صدوق', nameFr: 'Seddouk' },
    { nameAr: 'بني مليكش', nameFr: 'Beni-Mallikeche' },
    { nameAr: 'بو جليل', nameFr: 'Boudjellil' },
    { nameAr: 'تازمالت', nameFr: 'Tazmalt' },
    { nameAr: 'أكفادو', nameFr: 'Akfadou' },
    { nameAr: 'شميني', nameFr: 'Chemini' },
    { nameAr: 'سوق اوفلا', nameFr: 'Souk Oufella' },
    { nameAr: 'طيبان', nameFr: 'Tibane' },
    { nameAr: 'أوزلاقن', nameFr: 'Ouzellaguen' },
    { nameAr: 'أميزور', nameFr: 'Amizour' },
  ],
  7: [
    { nameAr: 'الفيض', nameFr: 'El Feidh' },
    { nameAr: 'ليشانة', nameFr: 'Lichana' },
    { nameAr: 'بوشقرون', nameFr: 'Bouchakroun' },
    { nameAr: 'مخادمة', nameFr: 'Mekhadma' },
    { nameAr: 'خنقة سيدي ناجي', nameFr: 'Khenguet Sidi Nadji' },
    { nameAr: 'زريبة الوادي', nameFr: 'Zeribet El Oued' },
    { nameAr: 'المزيرعة', nameFr: 'Meziraa' },
    { nameAr: 'بسكرة', nameFr: 'Biskra' },
    { nameAr: 'الحاجب', nameFr: 'El Hadjab' },
    { nameAr: 'مليلي', nameFr: 'M\'lili' },
    { nameAr: 'فوغالة', nameFr: 'Foughala' },
    { nameAr: 'الغروس', nameFr: 'El Ghrous' },
    { nameAr: 'برج بن عزوز', nameFr: 'Bordj Ben Azzouz' },
    { nameAr: 'أورلال', nameFr: 'Ourlal' },
    { nameAr: 'أوماش', nameFr: 'Oumache' },
    { nameAr: 'عين الناقة', nameFr: 'Ain Naga' },
    { nameAr: 'شتمة', nameFr: 'Chetma' },
    { nameAr: 'الحوش', nameFr: 'El Haouch' },
    { nameAr: 'سيدي عقبة', nameFr: 'Sidi Okba' },
    { nameAr: 'مشونش', nameFr: 'M\'chouneche' },
    { nameAr: 'ليوة', nameFr: 'Lioua' },
    { nameAr: 'طولقة', nameFr: 'Tolga' },
  ],
  8: [
    { nameAr: 'بشار', nameFr: 'Bechar' },
    { nameAr: 'بوكايس', nameFr: 'Boukais' },
    { nameAr: 'لحمر', nameFr: 'Lahmar' },
    { nameAr: 'موغل', nameFr: 'Mogheul' },
    { nameAr: 'المريجة', nameFr: 'Meridja' },
    { nameAr: 'تاغيت', nameFr: 'Taghit' },
    { nameAr: 'العبادلة', nameFr: 'Abadla' },
    { nameAr: 'عرق فراج', nameFr: 'Erg-Ferradj' },
    { nameAr: 'مشرع هواري بومدين', nameFr: 'Machraa-Houari-Boumediene' },
    { nameAr: 'بني ونيف', nameFr: 'Beni-Ounif' },
    { nameAr: 'تبلبالة', nameFr: 'Tabelbala' },
    { nameAr: 'القنادسة', nameFr: 'Kenadsa' },
  ],
  9: [
    { nameAr: 'بني مراد', nameFr: 'Beni Mered' },
    { nameAr: 'اولاد سلامة', nameFr: 'Ouled Slama' },
    { nameAr: 'موزاية', nameFr: 'Mouzaia' },
    { nameAr: 'حمام ملوان', nameFr: 'Hammam Elouane' },
    { nameAr: 'بوقرة', nameFr: 'Bougara' },
    { nameAr: 'صوحان', nameFr: 'Souhane' },
    { nameAr: 'الأربعاء', nameFr: 'Larbaa' },
    { nameAr: 'الصومعة', nameFr: 'Soumaa' },
    { nameAr: 'قرواو', nameFr: 'Guerrouaou' },
    { nameAr: 'بوفاريك', nameFr: 'Boufarik' },
    { nameAr: 'مفتاح', nameFr: 'Meftah' },
    { nameAr: 'الشفة', nameFr: 'Chiffa' },
    { nameAr: 'عين الرمانة', nameFr: 'Ain Romana' },
    { nameAr: 'وادي جر', nameFr: 'Oued  Djer' },
    { nameAr: 'العفرون', nameFr: 'El-Affroun' },
    { nameAr: 'أولاد يعيش', nameFr: 'Ouled Yaich' },
    { nameAr: 'الشريعة', nameFr: 'Chrea' },
    { nameAr: 'جبابرة', nameFr: 'Djebabra' },
    { nameAr: 'وادي العلايق', nameFr: 'Oued El Alleug' },
    { nameAr: 'بن خليل', nameFr: 'Benkhelil' },
    { nameAr: 'بني تامو', nameFr: 'Beni-Tamou' },
    { nameAr: 'الشبلي', nameFr: 'Chebli' },
    { nameAr: 'بوعينان', nameFr: 'Bouinan' },
    { nameAr: 'بوعرفة', nameFr: 'Bouarfa' },
    { nameAr: 'البليدة', nameFr: 'Blida' },
  ],
  10: [
    { nameAr: 'عين العلوي', nameFr: 'Ain Laloui' },
    { nameAr: 'الحجرة الزرقاء', nameFr: 'Hadjera Zerga' },
    { nameAr: 'مزدور', nameFr: 'Mezdour' },
    { nameAr: 'تاقديت', nameFr: 'Taguedite' },
    { nameAr: 'ريدان', nameFr: 'Ridane' },
    { nameAr: 'المعمورة', nameFr: 'Maamora' },
    { nameAr: 'الحاكمية', nameFr: 'El-Hakimia' },
    { nameAr: 'أهل القصر', nameFr: 'Ahl El Ksar' },
    { nameAr: 'ديرة', nameFr: 'Dirah' },
    { nameAr: 'الدشمية', nameFr: 'Dechmia' },
    { nameAr: 'بشلول', nameFr: 'Bechloul' },
    { nameAr: 'آث  منصور', nameFr: 'Ath Mansour' },
    { nameAr: 'سحاريج', nameFr: 'Saharidj' },
    { nameAr: 'العجيبة', nameFr: 'El Adjiba' },
    { nameAr: 'الأسنام', nameFr: 'El Asnam' },
    { nameAr: 'أمشدالة', nameFr: 'M Chedallah' },
    { nameAr: 'برج أوخريص', nameFr: 'Bordj Okhriss' },
    { nameAr: 'سور الغزلان', nameFr: 'Sour El Ghozlane' },
    { nameAr: 'حنيف', nameFr: 'Hanif' },
    { nameAr: 'شرفة', nameFr: 'Chorfa' },
    { nameAr: 'أولاد راشد', nameFr: 'Ouled Rached' },
    { nameAr: 'عين الحجر', nameFr: 'Ain El Hadjar' },
    { nameAr: 'أغبالو', nameFr: 'Aghbalou' },
    { nameAr: 'روراوة', nameFr: 'Raouraoua' },
    { nameAr: 'الخبوزية', nameFr: 'El Khabouzia' },
    { nameAr: 'بئر غبالو', nameFr: 'Bir Ghbalou' },
    { nameAr: 'البويرة', nameFr: 'Bouira' },
    { nameAr: 'عين الترك', nameFr: 'Ain Turk' },
    { nameAr: 'أيت لعزيز', nameFr: 'Ait Laaziz' },
    { nameAr: 'عين بسام', nameFr: 'Ain-Bessem' },
    { nameAr: 'المقراني', nameFr: 'El-Mokrani' },
    { nameAr: 'سوق الخميس', nameFr: 'Souk El Khemis' },
    { nameAr: 'أعمر', nameFr: 'Aomar' },
    { nameAr: 'جباحية', nameFr: 'Djebahia' },
    { nameAr: 'الهاشمية', nameFr: 'El Hachimia' },
    { nameAr: 'حيزر', nameFr: 'Haizer' },
    { nameAr: 'تاغزوت', nameFr: 'Taghzout' },
    { nameAr: 'بودربالة', nameFr: 'Bouderbala' },
    { nameAr: 'بوكرم', nameFr: 'Boukram' },
    { nameAr: 'قرومة', nameFr: 'Guerrouma' },
    { nameAr: 'الأخضرية', nameFr: 'Lakhdaria' },
    { nameAr: 'معلة', nameFr: 'Maala' },
    { nameAr: 'قادرية', nameFr: 'Kadiria' },
    { nameAr: 'زبربر', nameFr: 'Z\'barbar (El Isseri )' },
    { nameAr: 'وادي البردي', nameFr: 'Oued El Berdi' },
  ],
  11: [
    { nameAr: 'تاظروك', nameFr: 'Tazrouk' },
    { nameAr: 'ابلسة', nameFr: 'Abelsa' },
    { nameAr: 'تمنراست', nameFr: 'Tamanrasset' },
    { nameAr: 'عين امقل', nameFr: 'Ain Amguel' },
    { nameAr: 'أدلس', nameFr: 'Idles' },
  ],
  12: [
    { nameAr: 'الحويجبات', nameFr: 'El-Houidjbet' },
    { nameAr: 'العوينات', nameFr: 'El-Aouinet' },
    { nameAr: 'بئر مقدم', nameFr: 'Bir Mokkadem' },
    { nameAr: 'بئر الذهب', nameFr: 'Bir Dheheb' },
    { nameAr: 'صفصاف الوسرى', nameFr: 'Saf Saf El Ouesra' },
    { nameAr: 'قريقر', nameFr: 'Guorriguer' },
    { nameAr: 'بكارية', nameFr: 'Bekkaria' },
    { nameAr: 'بولحاف الدير', nameFr: 'Boulhaf Dyr' },
    { nameAr: 'أم علي', nameFr: 'Oum Ali' },
    { nameAr: 'بوخضرة', nameFr: 'Boukhadra' },
    { nameAr: 'الماء الابيض', nameFr: 'El Malabiod' },
    { nameAr: 'الونزة', nameFr: 'Ouenza' },
    { nameAr: 'المريج', nameFr: 'El Meridj' },
    { nameAr: 'عين الزرقاء', nameFr: 'Ain Zerga' },
    { nameAr: 'سطح قنطيس', nameFr: 'Stah Guentis' },
    { nameAr: 'العقلة', nameFr: 'El Ogla' },
    { nameAr: 'المزرعة', nameFr: 'El Mezeraa' },
    { nameAr: 'بجن', nameFr: 'Bedjene' },
    { nameAr: 'مرسط', nameFr: 'Morsott' },
    { nameAr: 'ثليجان', nameFr: 'Telidjen' },
    { nameAr: 'الشريعة', nameFr: 'Cheria' },
    { nameAr: 'تبسة', nameFr: 'Tebessa' },
    { nameAr: 'الحمامات', nameFr: 'Hammamet' },
    { nameAr: 'الكويف', nameFr: 'El Kouif' },
  ],
  13: [
    { nameAr: 'باب العسة', nameFr: 'Bab El Assa' },
    { nameAr: 'تيرني بني هديل', nameFr: 'Terny Beni Hediel' },
    { nameAr: 'منصورة', nameFr: 'Mansourah' },
    { nameAr: 'بني مستر', nameFr: 'Beni Mester' },
    { nameAr: 'عين غرابة', nameFr: 'Ain Ghoraba' },
    { nameAr: 'شتوان', nameFr: 'Chetouane' },
    { nameAr: 'عمير', nameFr: 'Amieur' },
    { nameAr: 'عين فزة', nameFr: 'Ain Fezza' },
    { nameAr: 'هنين', nameFr: 'Honnaine' },
    { nameAr: 'بني خلاد', nameFr: 'Beni Khellad' },
    { nameAr: 'ندرومة', nameFr: 'Nedroma' },
    { nameAr: 'مسيردة الفواقة', nameFr: 'M\'sirda Fouaga' },
    { nameAr: 'مرسى بن مهيدي', nameFr: 'Marsa Ben M\'hidi' },
    { nameAr: 'سيدي مجاهد', nameFr: 'Sidi Medjahed' },
    { nameAr: 'بني بوسعيد', nameFr: 'Beni Boussaid' },
    { nameAr: 'سبدو', nameFr: 'Sebdou' },
    { nameAr: 'بوحلو', nameFr: 'Bouhlou' },
    { nameAr: 'مغنية', nameFr: 'Maghnia' },
    { nameAr: 'حمام بوغرارة', nameFr: 'Hammam Boughrara' },
    { nameAr: 'زناتة', nameFr: 'Zenata' },
    { nameAr: 'أولاد رياح', nameFr: 'Ouled Riyah' },
    { nameAr: 'الحناية', nameFr: 'Hennaya' },
    { nameAr: 'سيدي العبدلي', nameFr: 'Sidi Abdelli' },
    { nameAr: 'سوق الثلاثاء', nameFr: 'Souk Tleta' },
    { nameAr: 'بن سكران', nameFr: 'Bensekrane' },
    { nameAr: 'فلاوسن', nameFr: 'Fellaoucene' },
    { nameAr: 'عين الكبيرة', nameFr: 'Ain Kebira' },
    { nameAr: 'عين فتاح', nameFr: 'Ain Fetah' },
    { nameAr: 'تلمسان', nameFr: 'Tlemcen' },
    { nameAr: 'عين النحالة', nameFr: 'Ain Nehala' },
    { nameAr: 'عين تالوت', nameFr: 'Ain Tellout' },
    { nameAr: 'عين يوسف', nameFr: 'Ain Youcef' },
    { nameAr: 'بني وارسوس', nameFr: 'Beni Ouarsous' },
    { nameAr: 'الفحول', nameFr: 'El Fehoul' },
    { nameAr: 'الرمشي', nameFr: 'Remchi' },
    { nameAr: 'سبعة شيوخ', nameFr: 'Sebbaa Chioukh' },
    { nameAr: 'السواني', nameFr: 'Souani' },
    { nameAr: 'صبرة', nameFr: 'Sabra' },
    { nameAr: 'دار يغمراسن', nameFr: 'Dar Yaghmoracen' },
    { nameAr: 'الغزوات', nameFr: 'Ghazaouet' },
    { nameAr: 'السواحلية', nameFr: 'Souahlia' },
    { nameAr: 'تيانت', nameFr: 'Tianet' },
    { nameAr: 'بني صميل', nameFr: 'Beni Smiel' },
    { nameAr: 'وادي الخضر', nameFr: 'Oued Lakhdar' },
    { nameAr: 'أولاد ميمون', nameFr: 'Ouled Mimoun' },
    { nameAr: 'بني بهدل', nameFr: 'Beni Bahdel' },
    { nameAr: 'بني سنوس', nameFr: 'Beni Snous' },
    { nameAr: 'العزايل', nameFr: 'Azail' },
    { nameAr: 'جبالة', nameFr: 'Djebala' },
  ],
  14: [
    { nameAr: 'مهدية', nameFr: 'Mahdia' },
    { nameAr: 'عين دزاريت', nameFr: 'Ain Dzarit' },
    { nameAr: 'السبعين', nameFr: 'Sebaine' },
    { nameAr: 'الفايجة', nameFr: 'Faidja' },
    { nameAr: 'سي عبد الغني', nameFr: 'Si Abdelghani' },
    { nameAr: 'السوقر', nameFr: 'Sougueur' },
    { nameAr: 'توسنينة', nameFr: 'Tousnina' },
    { nameAr: 'مغيلة', nameFr: 'Meghila' },
    { nameAr: 'السبت', nameFr: 'Sebt' },
    { nameAr: 'سيدي حسني', nameFr: 'Sidi Hosni' },
    { nameAr: 'عين الحديد', nameFr: 'Ain El Hadid' },
    { nameAr: 'فرندة', nameFr: 'Frenda' },
    { nameAr: 'تخمرت', nameFr: 'Takhemaret' },
    { nameAr: 'عين كرمس', nameFr: 'Ain Kermes' },
    { nameAr: 'جبيلات الرصفاء', nameFr: 'Djebilet Rosfa' },
    { nameAr: 'مادنة', nameFr: 'Madna' },
    { nameAr: 'مدريسة', nameFr: 'Medrissa' },
    { nameAr: 'سيدي عبد الرحمن', nameFr: 'Sidi Abderrahmane' },
    { nameAr: 'قرطوفة', nameFr: 'Guertoufa' },
    { nameAr: 'وادي ليلي', nameFr: 'Oued Lilli' },
    { nameAr: 'سيدي علي ملال', nameFr: 'Sidi Ali Mellal' },
    { nameAr: 'جيلالي بن عمار', nameFr: 'Djillali Ben Amar' },
    { nameAr: 'مشرع الصفا', nameFr: 'Mechraa Safa' },
    { nameAr: 'تاقدمت', nameFr: 'Tagdempt' },
    { nameAr: 'تيدة', nameFr: 'Tidda' },
    { nameAr: 'الناظورة', nameFr: 'Nadorah' },
    { nameAr: 'تيارت', nameFr: 'Tiaret' },
    { nameAr: 'مدروسة', nameFr: 'Medroussa' },
    { nameAr: 'ملاكو', nameFr: 'Mellakou' },
    { nameAr: 'سيدي بختي', nameFr: 'Sidi Bakhti' },
    { nameAr: 'عين الذهب', nameFr: 'Ain Deheb' },
    { nameAr: 'شحيمة', nameFr: 'Chehaima' },
    { nameAr: 'النعيمة', nameFr: 'Naima' },
    { nameAr: 'عين بوشقيف', nameFr: 'Ain Bouchekif' },
    { nameAr: 'دحموني', nameFr: 'Dahmouni' },
    { nameAr: 'الرحوية', nameFr: 'Rahouia' },
  ],
  15: [
    { nameAr: 'ميزرانـــة', nameFr: 'Mizrana' },
    { nameAr: 'إيجــار', nameFr: 'Idjeur' },
    { nameAr: 'بني دوالة', nameFr: 'Beni-Douala' },
    { nameAr: 'بني زيكــي', nameFr: 'Beni-Zikki' },
    { nameAr: 'إيلولة أومـــالو', nameFr: 'Illoula Oumalou' },
    { nameAr: 'أقني قغران', nameFr: 'Agouni-Gueghrane' },
    { nameAr: 'أيت بــوادو', nameFr: 'Ait Bouaddou' },
    { nameAr: 'واضية', nameFr: 'Ouadhias' },
    { nameAr: 'تيزي نثلاثة', nameFr: 'Tizi N\'tleta' },
    { nameAr: 'أغريب', nameFr: 'Aghribs' },
    { nameAr: 'أيت شافع', nameFr: 'Ait-Chafaa' },
    { nameAr: 'أقرو', nameFr: 'Akerrou' },
    { nameAr: 'أزفون', nameFr: 'Azeffoun' },
    { nameAr: 'إفليـــسن', nameFr: 'Iflissen' },
    { nameAr: 'تيقـزيرت', nameFr: 'Tigzirt' },
    { nameAr: 'أسي يوسف', nameFr: 'Assi-Youcef' },
    { nameAr: 'بوغني', nameFr: 'Boghni' },
    { nameAr: 'بونوح', nameFr: 'Bounouh' },
    { nameAr: 'مشطراس', nameFr: 'Mechtras' },
    { nameAr: 'ذراع بن خدة', nameFr: 'Draa-Ben-Khedda' },
    { nameAr: 'سيدي نعمان', nameFr: 'Sidi Namane' },
    { nameAr: 'تادمايت', nameFr: 'Tadmait' },
    { nameAr: 'تيرمتين', nameFr: 'Tirmitine' },
    { nameAr: 'أيت بومهدي', nameFr: 'Ait Boumahdi' },
    { nameAr: 'أيت تودرت', nameFr: 'Ait-Toudert' },
    { nameAr: 'بني عيسي', nameFr: 'Beni-Aissi' },
    { nameAr: 'واسيف', nameFr: 'Ouacif' },
    { nameAr: 'أيت خليلي', nameFr: 'Ait Khellili' },
    { nameAr: 'مقــلع', nameFr: 'Mekla' },
    { nameAr: 'صوامـــع', nameFr: 'Souama' },
    { nameAr: 'بني يني', nameFr: 'Beni-Yenni' },
    { nameAr: 'إبودرارن', nameFr: 'Iboudrarene' },
    { nameAr: 'تيزي وزو', nameFr: 'Tizi-Ouzou' },
    { nameAr: 'أبي يوسف', nameFr: 'Abi-Youcef' },
    { nameAr: 'عين الحمام', nameFr: 'Ain-El-Hammam' },
    { nameAr: 'أيت يحيى', nameFr: 'Ait-Yahia' },
    { nameAr: 'اقبيل', nameFr: 'Akbil' },
    { nameAr: 'بوجيمة', nameFr: 'Boudjima' },
    { nameAr: 'ماكودة', nameFr: 'Makouda' },
    { nameAr: 'عين الزاوية', nameFr: 'Ain-Zaouia' },
    { nameAr: 'أيت يحي موسى', nameFr: 'Ait Yahia Moussa' },
    { nameAr: 'ذراع الميزان', nameFr: 'Draa-El-Mizan' },
    { nameAr: 'فريقات', nameFr: 'Frikat' },
    { nameAr: 'مكيرة', nameFr: 'M\'kira' },
    { nameAr: 'تيزي غنيف', nameFr: 'Tizi-Gheniff' },
    { nameAr: 'يطــافن', nameFr: 'Yatafene' },
    { nameAr: 'إيلـيــلتـن', nameFr: 'Illilten' },
    { nameAr: 'إمســوحال', nameFr: 'Imsouhal' },
    { nameAr: 'عزازقة', nameFr: 'Azazga' },
    { nameAr: 'فريحة', nameFr: 'Freha' },
    { nameAr: 'إيفيغاء', nameFr: 'Ifigha' },
    { nameAr: 'إعــكورن', nameFr: 'Yakourene' },
    { nameAr: 'زكري', nameFr: 'Zekri' },
    { nameAr: 'أيت عقـواشة', nameFr: 'Ait Aggouacha' },
    { nameAr: 'إيرجـــن', nameFr: 'Irdjen' },
    { nameAr: 'الأربعــاء ناث إيراثن', nameFr: 'Larbaa Nath Irathen' },
    { nameAr: 'أيت  أومالو', nameFr: 'Ait-Oumalou' },
    { nameAr: 'تيزي راشد', nameFr: 'Tizi-Rached' },
    { nameAr: 'أيت عيسى ميمون', nameFr: 'Ait-Aissa-Mimoun' },
    { nameAr: 'واقنون', nameFr: 'Ouaguenoun' },
    { nameAr: 'تيمـيزار', nameFr: 'Timizart' },
    { nameAr: 'معـــاتقة', nameFr: 'Maatkas' },
    { nameAr: 'سوق الإثنين', nameFr: 'Souk-El-Tenine' },
    { nameAr: 'أيت محمود', nameFr: 'Ait-Mahmoud' },
    { nameAr: 'بنــــي زمنزار', nameFr: 'Beni Zmenzer' },
    { nameAr: 'إفــرحــونان', nameFr: 'Iferhounene' },
    { nameAr: 'بوزقــن', nameFr: 'Bouzeguene' },
  ],
  16: [
    { nameAr: 'حسين داي', nameFr: 'Hussein Dey' },
    { nameAr: 'الكاليتوس', nameFr: 'Les Eucalyptus' },
    { nameAr: 'سيدي موسى', nameFr: 'Sidi Moussa' },
    { nameAr: 'القبة', nameFr: 'Kouba' },
    { nameAr: 'محمد بلوزداد', nameFr: 'Mohamed Belouzdad' },
    { nameAr: 'عين طاية', nameFr: 'Ain Taya' },
    { nameAr: 'باب الزوار', nameFr: 'Bab Ezzouar' },
    { nameAr: 'برج الكيفان', nameFr: 'Bordj El Kiffan' },
    { nameAr: 'الدار البيضاء', nameFr: 'Dar El Beida' },
    { nameAr: 'المرسى', nameFr: 'El Marsa' },
    { nameAr: 'المحمدية', nameFr: 'Mohammadia' },
    { nameAr: 'بئر توتة', nameFr: 'Bir Touta' },
    { nameAr: 'اولاد شبل', nameFr: 'Ouled Chebel' },
    { nameAr: 'تسالة المرجة', nameFr: 'Tessala El Merdja' },
    { nameAr: 'هراوة', nameFr: 'Herraoua' },
    { nameAr: 'رغاية', nameFr: 'Reghaia' },
    { nameAr: 'الرويبة', nameFr: 'Rouiba' },
    { nameAr: 'المعالمة', nameFr: 'Maalma' },
    { nameAr: 'الرحمانية', nameFr: 'Rahmania' },
    { nameAr: 'سويدانية', nameFr: 'Souidania' },
    { nameAr: 'سطاوالي', nameFr: 'Staoueli' },
    { nameAr: 'زرالدة', nameFr: 'Zeralda' },
    { nameAr: 'بابا حسن', nameFr: 'Baba Hassen' },
    { nameAr: 'الدويرة', nameFr: 'Douira' },
    { nameAr: 'الدرارية', nameFr: 'Draria' },
    { nameAr: 'العاشور', nameFr: 'El Achour' },
    { nameAr: 'الخرايسية', nameFr: 'Khraissia' },
    { nameAr: 'عين بنيان', nameFr: 'Ain Benian' },
    { nameAr: 'الشراقة', nameFr: 'Cheraga' },
    { nameAr: 'دالي ابراهيم', nameFr: 'Dely Ibrahim' },
    { nameAr: 'الحمامات', nameFr: 'Hammamet' },
    { nameAr: 'اولاد فايت', nameFr: 'Ouled Fayet' },
    { nameAr: 'الجزائر الوسطى', nameFr: 'Alger Centre' },
    { nameAr: 'المدنية', nameFr: 'El Madania' },
    { nameAr: 'المرادية', nameFr: 'El Mouradia' },
    { nameAr: 'سيدي امحمد', nameFr: 'Sidi M\'hamed' },
    { nameAr: 'السحاولة', nameFr: 'Sehaoula' },
    { nameAr: 'بولوغين بن زيري', nameFr: 'Bologhine Ibnou Ziri' },
    { nameAr: 'القصبة', nameFr: 'Casbah' },
    { nameAr: 'وادي قريش', nameFr: 'Oued Koriche' },
    { nameAr: 'الرايس حميدو', nameFr: 'Rais Hamidou' },
    { nameAr: 'بئر مراد رايس', nameFr: 'Bir Mourad Rais' },
    { nameAr: 'بئر خادم', nameFr: 'Birkhadem' },
    { nameAr: 'جسر قسنطينة', nameFr: 'Djasr Kasentina' },
    { nameAr: 'حيدرة', nameFr: 'Hydra' },
    { nameAr: 'المغارية', nameFr: 'El Magharia' },
    { nameAr: 'ابن عكنون', nameFr: 'Ben Aknoun' },
    { nameAr: 'بني مسوس', nameFr: 'Beni Messous' },
    { nameAr: 'بوزريعة', nameFr: 'Bouzareah' },
    { nameAr: 'الابيار', nameFr: 'El Biar' },
    { nameAr: 'باش جراح', nameFr: 'Bachedjerah' },
    { nameAr: 'بوروبة', nameFr: 'Bourouba' },
    { nameAr: 'الحراش', nameFr: 'El Harrach' },
    { nameAr: 'وادي السمار', nameFr: 'Oued Smar' },
    { nameAr: 'براقي', nameFr: 'Baraki' },
    { nameAr: 'برج البحري', nameFr: 'Bordj El Bahri' },
    { nameAr: 'باب الوادي', nameFr: 'Bab El Oued' },
  ],
  17: [
    { nameAr: 'حاسي العش', nameFr: 'Hassi El Euch' },
    { nameAr: 'عين الإبل', nameFr: 'Ain El Ibel' },
    { nameAr: 'القديد', nameFr: 'El Guedid' },
    { nameAr: 'الشارف', nameFr: 'Charef' },
    { nameAr: 'بن يعقوب', nameFr: 'Benyagoub' },
    { nameAr: 'سيدي بايزيد', nameFr: 'Sidi Baizid' },
    { nameAr: 'مليليحة', nameFr: 'M\'liliha' },
    { nameAr: 'دار الشيوخ', nameFr: 'Dar Chioukh' },
    { nameAr: 'تعظميت', nameFr: 'Taadmit' },
    { nameAr: 'زكار', nameFr: 'Zaccar' },
    { nameAr: 'دويس', nameFr: 'Douis' },
    { nameAr: 'الادريسية', nameFr: 'El Idrissia' },
    { nameAr: 'عين الشهداء', nameFr: 'Ain Chouhada' },
    { nameAr: 'الجلفة', nameFr: 'Djelfa' },
    { nameAr: 'زعفران', nameFr: 'Zaafrane' },
    { nameAr: 'عين معبد', nameFr: 'Ain Maabed' },
    { nameAr: 'حاسي بحبح', nameFr: 'Hassi Bahbah' },
    { nameAr: 'مجبارة', nameFr: 'Moudjebara' },
  ],
  18: [
    { nameAr: 'جيجل', nameFr: 'Jijel' },
    { nameAr: 'العوانة', nameFr: 'El Aouana' },
    { nameAr: 'سلمى بن زيادة', nameFr: 'Selma Benziada' },
    { nameAr: 'أراقن سويسي', nameFr: 'Erraguene Souissi' },
    { nameAr: 'بوسيف أولاد عسكر', nameFr: 'Boussif Ouled Askeur' },
    { nameAr: 'زيامة منصورية', nameFr: 'Ziama Mansouriah' },
    { nameAr: 'الشحنة', nameFr: 'Chahna' },
    { nameAr: 'الامير عبد القادر', nameFr: 'Emir Abdelkader' },
    { nameAr: 'وجانة', nameFr: 'Oudjana' },
    { nameAr: 'الطاهير', nameFr: 'Taher' },
    { nameAr: 'الشقفة', nameFr: 'Chekfa' },
    { nameAr: 'القنار نشفي', nameFr: 'El Kennar Nouchfi' },
    { nameAr: 'سيدي عبد العزيز', nameFr: 'Sidi Abdelaziz' },
    { nameAr: 'الميلية', nameFr: 'El Milia' },
    { nameAr: 'أولاد يحيى خدروش', nameFr: 'Ouled Yahia Khadrouch' },
    { nameAr: 'أولاد رابح', nameFr: 'Ouled Rabah' },
    { nameAr: 'سيدي معروف', nameFr: 'Sidi Marouf' },
    { nameAr: 'غبالة', nameFr: 'Ghebala' },
    { nameAr: 'السطارة', nameFr: 'Settara' },
    { nameAr: 'بوراوي بلهادف', nameFr: 'Bouraoui Belhadef' },
    { nameAr: 'العنصر', nameFr: 'El Ancer' },
    { nameAr: 'خيري واد عجول', nameFr: 'Khiri Oued Adjoul' },
    { nameAr: 'جيملة', nameFr: 'Djimla' },
    { nameAr: 'قاوس', nameFr: 'Kaous' },
    { nameAr: 'تاكسنة', nameFr: 'Texenna' },
    { nameAr: 'برج الطهر', nameFr: 'Bordj T\'har' },
    { nameAr: 'بودريعة بني  ياجيس', nameFr: 'Boudria Beniyadjis' },
    { nameAr: 'الجمعة بني حبيبي', nameFr: 'Djemaa Beni Habibi' },
  ],
  19: [
    { nameAr: 'الرصفة', nameFr: 'Rosfa' },
    { nameAr: 'واد البارد', nameFr: 'Oued El Bared' },
    { nameAr: 'تيزي نبشار', nameFr: 'Tizi N\'bechar' },
    { nameAr: 'مزلوق', nameFr: 'Mezloug' },
    { nameAr: 'قلال', nameFr: 'Guellal' },
    { nameAr: 'قصر الابطال', nameFr: 'Kasr El Abtal' },
    { nameAr: 'أولاد سي أحمد', nameFr: 'Ouled Si Ahmed' },
    { nameAr: 'أيت نوال مزادة', nameFr: 'Ait Naoual Mezada' },
    { nameAr: 'ايت تيزي', nameFr: 'Ait-Tizi' },
    { nameAr: 'بوعنداس', nameFr: 'Bouandas' },
    { nameAr: 'بوسلام', nameFr: 'Bousselam' },
    { nameAr: 'حمام السخنة', nameFr: 'Hamam Soukhna' },
    { nameAr: 'الطاية', nameFr: 'Taya' },
    { nameAr: 'التلة', nameFr: 'Tella' },
    { nameAr: 'عين ولمان', nameFr: 'Ain Oulmene' },
    { nameAr: 'بوطالب', nameFr: 'Boutaleb' },
    { nameAr: 'الحامة', nameFr: 'Hamma' },
    { nameAr: 'أولاد تبان', nameFr: 'Ouled Tebben' },
    { nameAr: 'عموشة', nameFr: 'Amoucha' },
    { nameAr: 'صالح باي', nameFr: 'Salah Bey' },
    { nameAr: 'عين أزال', nameFr: 'Ain Azel' },
    { nameAr: 'عين الحجر', nameFr: 'Ain Lahdjar' },
    { nameAr: 'بيضاء برج', nameFr: 'Beidha Bordj' },
    { nameAr: 'بئر حدادة', nameFr: 'Bir Haddada' },
    { nameAr: 'قنزات', nameFr: 'Guenzet' },
    { nameAr: 'حربيل', nameFr: 'Harbil' },
    { nameAr: 'عين الروى', nameFr: 'Ain-Roua' },
    { nameAr: 'بني وسين', nameFr: 'Beni Oussine' },
    { nameAr: 'أوريسيا', nameFr: 'El Ouricia' },
    { nameAr: 'بوقاعة', nameFr: 'Bougaa' },
    { nameAr: 'ذراع قبيلة', nameFr: 'Draa-Kebila' },
    { nameAr: 'حمام قرقور', nameFr: 'Hammam Guergour' },
    { nameAr: 'سطيف', nameFr: 'Setif' },
    { nameAr: 'عين الكبيرة', nameFr: 'Ain El Kebira' },
    { nameAr: 'الدهامشة', nameFr: 'Dehamcha' },
    { nameAr: 'أولاد عدوان', nameFr: 'Ouled Addouane' },
    { nameAr: 'عين السبت', nameFr: 'Ain-Sebt' },
    { nameAr: 'بني عزيز', nameFr: 'Beni-Aziz' },
    { nameAr: 'معاوية', nameFr: 'Maaouia' },
    { nameAr: 'بلاعة', nameFr: 'Bellaa' },
    { nameAr: 'بئر العرش', nameFr: 'Bir-El-Arch' },
    { nameAr: 'الولجة', nameFr: 'El-Ouldja' },
    { nameAr: 'تاشودة', nameFr: 'Tachouda' },
    { nameAr: 'تالة إيفاسن', nameFr: 'Tala-Ifacene' },
    { nameAr: 'سرج الغول', nameFr: 'Serdj-El-Ghoul' },
    { nameAr: 'قجال', nameFr: 'Guidjel' },
    { nameAr: 'أولاد صابر', nameFr: 'Ouled Sabor' },
    { nameAr: 'بازر سكرة', nameFr: 'Bazer-Sakra' },
    { nameAr: 'العلمة', nameFr: 'El Eulma' },
    { nameAr: 'قلتة زرقاء', nameFr: 'Guelta Zerka' },
    { nameAr: 'بني فودة', nameFr: 'Beni Fouda' },
    { nameAr: 'جميلة', nameFr: 'Djemila' },
    { nameAr: 'عين لقراج', nameFr: 'Ain-Legradj' },
    { nameAr: 'بني شبانة', nameFr: 'Beni Chebana' },
    { nameAr: 'بني ورتيلان', nameFr: 'Beni Ourtilane' },
    { nameAr: 'بني موحلي', nameFr: 'Beni-Mouhli' },
    { nameAr: 'عين عباسة', nameFr: 'Ain Abessa' },
    { nameAr: 'عين أرنات', nameFr: 'Ain Arnat' },
    { nameAr: 'بابور', nameFr: 'Babor' },
    { nameAr: 'ماوكلان', nameFr: 'Maouaklane' },
  ],
  20: [
    { nameAr: 'سعيدة', nameFr: 'Saida' },
    { nameAr: 'تيرسين', nameFr: 'Tircine' },
    { nameAr: 'أولاد إبراهيم', nameFr: 'Ouled Brahim' },
    { nameAr: 'عين السلطان', nameFr: 'Ain Soltane' },
    { nameAr: 'المعمورة', nameFr: 'Maamora' },
    { nameAr: 'الحساسنة', nameFr: 'El Hassasna' },
    { nameAr: 'عين السخونة', nameFr: 'Ain Sekhouna' },
    { nameAr: 'سيدي بوبكر', nameFr: 'Sidi Boubekeur' },
    { nameAr: 'أولاد خالد', nameFr: 'Ouled Khaled' },
    { nameAr: 'هونت', nameFr: 'Hounet' },
    { nameAr: 'يوب', nameFr: 'Youb' },
    { nameAr: 'دوي ثابت', nameFr: 'Doui Thabet' },
    { nameAr: 'سيدي احمد', nameFr: 'Sidi Ahmed' },
    { nameAr: 'مولاي العربي', nameFr: 'Moulay Larbi' },
    { nameAr: 'عين الحجر', nameFr: 'Ain El Hadjar' },
    { nameAr: 'سيدي عمر', nameFr: 'Sidi Amar' },
  ],
  21: [
    { nameAr: 'عين بوزيان', nameFr: 'Ain Bouziane' },
    { nameAr: 'صالح بو الشعور', nameFr: 'Salah Bouchaour' },
    { nameAr: 'الحدائق', nameFr: 'El Hadaiek' },
    { nameAr: 'زردازة', nameFr: 'Zerdezas' },
    { nameAr: 'أولاد حبابة', nameFr: 'Ouled Habbaba' },
    { nameAr: 'بني ولبان', nameFr: 'Beni Oulbane' },
    { nameAr: 'سيدي مزغيش', nameFr: 'Sidi Mezghiche' },
    { nameAr: 'بني بشير', nameFr: 'Beni Bechir' },
    { nameAr: 'رمضان جمال', nameFr: 'Ramdane Djamel' },
    { nameAr: 'بين الويدان', nameFr: 'Bin El Ouiden' },
    { nameAr: 'مجاز الدشيش', nameFr: 'Emjez Edchich' },
    { nameAr: 'تمالوس', nameFr: 'Tamalous' },
    { nameAr: 'عين قشرة', nameFr: 'Ain Kechra' },
    { nameAr: 'الولجة بولبلوط', nameFr: 'Ouldja Boulbalout' },
    { nameAr: 'أم الطوب', nameFr: 'Oum Toub' },
    { nameAr: 'الغدير', nameFr: 'El Ghedir' },
    { nameAr: 'الكركرة', nameFr: 'Kerkara' },
    { nameAr: 'الحروش', nameFr: 'El Arrouch' },
    { nameAr: 'الزيتونة', nameFr: 'Zitouna' },
    { nameAr: 'أولاد عطية', nameFr: 'Ouled Attia' },
    { nameAr: 'وادي الزهور', nameFr: 'Oued Zhour' },
    { nameAr: 'القل', nameFr: 'Collo' },
    { nameAr: 'الشرايع', nameFr: 'Cheraia' },
    { nameAr: 'بني زيد', nameFr: 'Beni Zid' },
    { nameAr: 'خناق مايو', nameFr: 'Khenag Maoune' },
    { nameAr: 'المرسى', nameFr: 'El Marsa' },
    { nameAr: 'بن عزوز', nameFr: 'Ben Azzouz' },
    { nameAr: 'بكوش لخضر', nameFr: 'Bekkouche Lakhdar' },
    { nameAr: 'السبت', nameFr: 'Es Sebt' },
    { nameAr: 'عين شرشار', nameFr: 'Ain Charchar' },
    { nameAr: 'عزابة', nameFr: 'Azzaba' },
    { nameAr: 'بوشطاطة', nameFr: 'Bouchetata' },
    { nameAr: 'فلفلة', nameFr: 'Filfila' },
    { nameAr: 'حمادي كرومة', nameFr: 'Hammadi Krouma' },
    { nameAr: 'سكيكدة', nameFr: 'Skikda' },
    { nameAr: 'عين زويت', nameFr: 'Ain Zouit' },
    { nameAr: 'جندل سعدي محمد', nameFr: 'Djendel Saadi Mohamed' },
    { nameAr: 'قنواع', nameFr: 'Kanoua' },
  ],
  22: [
    { nameAr: 'سيدي علي بن يوب', nameFr: 'Sidi Ali Benyoub' },
    { nameAr: 'مولاي سليسن', nameFr: 'Moulay Slissen' },
    { nameAr: 'الحصيبة', nameFr: 'El Hacaiba' },
    { nameAr: 'عين تندمين', nameFr: 'Ain Tindamine' },
    { nameAr: 'تنيرة', nameFr: 'Tenira' },
    { nameAr: 'وادي سفيون', nameFr: 'Oued Sefioun' },
    { nameAr: 'حاسي دحو', nameFr: 'Hassi Dahou' },
    { nameAr: 'وادي تاوريرة', nameFr: 'Oued Taourira' },
    { nameAr: 'بن عشيبة شلية', nameFr: 'Benachiba Chelia' },
    { nameAr: 'سيدي يعقوب', nameFr: 'Sidi Yacoub' },
    { nameAr: 'سيدي لحسن', nameFr: 'Sidi Lahcene' },
    { nameAr: 'سيدي خالد', nameFr: 'Sidi Khaled' },
    { nameAr: 'طابية', nameFr: 'Tabia' },
    { nameAr: 'سيدي ابراهيم', nameFr: 'Sidi Brahim' },
    { nameAr: 'العمارنة', nameFr: 'Amarnas' },
    { nameAr: 'بوخنفيس', nameFr: 'Boukhanefis' },
    { nameAr: 'حاسي زهانة', nameFr: 'Hassi Zahana' },
    { nameAr: 'شيطوان البلايلة', nameFr: 'Chetouane Belaila' },
    { nameAr: 'بن باديس', nameFr: 'Ben Badis' },
    { nameAr: 'بضرابين المقراني', nameFr: 'Bedrabine El Mokrani' },
    { nameAr: 'سفيزف', nameFr: 'Sfisef' },
    { nameAr: 'مسيد', nameFr: 'M\'cid' },
    { nameAr: 'بوجبهة البرج', nameFr: 'Boudjebaa El Bordj' },
    { nameAr: 'عين أدن', nameFr: 'Ain- Adden' },
    { nameAr: 'سيدي حمادوش', nameFr: 'Sidi Hamadouche' },
    { nameAr: 'سيدي شعيب', nameFr: 'Sidi Chaib' },
    { nameAr: 'مكدرة', nameFr: 'Makedra' },
    { nameAr: 'عين البرد', nameFr: 'Ain El Berd' },
    { nameAr: 'رجم دموش', nameFr: 'Redjem Demouche' },
    { nameAr: 'راس الماء', nameFr: 'Ras El Ma' },
    { nameAr: 'وادي السبع', nameFr: 'Oued Sebaa' },
    { nameAr: 'مرحوم', nameFr: 'Marhoum' },
    { nameAr: 'سيدي بلعباس', nameFr: 'Sidi Bel-Abbes' },
    { nameAr: 'عين الثريد', nameFr: 'Ain Thrid' },
    { nameAr: 'السهالة الثورة', nameFr: 'Sehala Thaoura' },
    { nameAr: 'تسالة', nameFr: 'Tessala' },
    { nameAr: 'بلعربي', nameFr: 'Belarbi' },
    { nameAr: 'مصطفى بن ابراهيم', nameFr: 'Mostefa  Ben Brahim' },
    { nameAr: 'تلموني', nameFr: 'Tilmouni' },
    { nameAr: 'زروالة', nameFr: 'Zerouala' },
    { nameAr: 'الضاية', nameFr: 'Dhaya' },
    { nameAr: 'مزاورو', nameFr: 'Mezaourou' },
    { nameAr: 'تغاليمت', nameFr: 'Teghalimet' },
    { nameAr: 'تلاغ', nameFr: 'Telagh' },
    { nameAr: 'عين قادة', nameFr: 'Ain Kada' },
    { nameAr: 'لمطار', nameFr: 'Lamtar' },
    { nameAr: 'سيدي علي بوسيدي', nameFr: 'Sidi Ali Boussidi' },
    { nameAr: 'سيدي دحو الزاير', nameFr: 'Sidi Dahou Zairs' },
    { nameAr: 'بئر الحمام', nameFr: 'Bir El Hammam' },
    { nameAr: 'مرين', nameFr: 'Merine' },
    { nameAr: 'تفسور', nameFr: 'Tefessour' },
    { nameAr: 'تاودموت', nameFr: 'Taoudmout' },
  ],
  23: [
    { nameAr: 'عنابة', nameFr: 'Annaba' },
    { nameAr: 'سرايدي', nameFr: 'Seraidi' },
    { nameAr: 'برحال', nameFr: 'Berrahal' },
    { nameAr: 'واد العنب', nameFr: 'Oued El Aneb' },
    { nameAr: 'الحجار', nameFr: 'El Hadjar' },
    { nameAr: 'سيدي عمار', nameFr: 'Sidi Amar' },
    { nameAr: 'البوني', nameFr: 'El Bouni' },
    { nameAr: 'عين الباردة', nameFr: 'Ain El Berda' },
    { nameAr: 'الشرفة', nameFr: 'Cheurfa' },
    { nameAr: 'العلمة', nameFr: 'El Eulma' },
    { nameAr: 'التريعات', nameFr: 'Treat' },
    { nameAr: 'شطايبي', nameFr: 'Chetaibi' },
  ],
  24: [
    { nameAr: 'نشماية', nameFr: 'Nechmaya' },
    { nameAr: 'بوحمدان', nameFr: 'Bou Hamdane' },
    { nameAr: 'حمام دباغ', nameFr: 'Hammam Debagh' },
    { nameAr: 'الركنية', nameFr: 'Roknia' },
    { nameAr: 'الدهوارة', nameFr: 'Dahouara' },
    { nameAr: 'حمام النبايل', nameFr: 'Hammam N\'bail' },
    { nameAr: 'قالمة', nameFr: 'Guelma' },
    { nameAr: 'بومهرة أحمد', nameFr: 'Boumahra Ahmed' },
    { nameAr: 'عين بن بيضاء', nameFr: 'Ain Ben Beida' },
    { nameAr: 'بوشقوف', nameFr: 'Bouchegouf' },
    { nameAr: 'مجاز الصفاء', nameFr: 'Medjez Sfa' },
    { nameAr: 'وادي فراغة', nameFr: 'Oued Ferragha' },
    { nameAr: 'بوعاتي محمود', nameFr: 'Bouati Mahmoud' },
    { nameAr: 'الفجوج', nameFr: 'El Fedjoudj' },
    { nameAr: 'هيليوبوليس', nameFr: 'Heliopolis' },
    { nameAr: 'مجاز عمار', nameFr: 'Medjez Amar' },
    { nameAr: 'هواري بومدين', nameFr: 'Houari Boumedienne' },
    { nameAr: 'رأس العقبة', nameFr: 'Ras El Agba' },
    { nameAr: 'سلاوة عنونة', nameFr: 'Sellaoua Announa' },
    { nameAr: 'جبالة الخميسي', nameFr: 'Djeballah Khemissi' },
    { nameAr: 'برج صباط', nameFr: 'Bordj Sabath' },
    { nameAr: 'وادي الزناتي', nameFr: 'Oued Zenati' },
    { nameAr: 'عين رقادة', nameFr: 'Ain Regada' },
    { nameAr: 'عين العربي', nameFr: 'Ain Larbi' },
    { nameAr: 'عين مخلوف', nameFr: 'Ain Makhlouf' },
    { nameAr: 'تاملوكة', nameFr: 'Tamlouka' },
    { nameAr: 'عين صندل', nameFr: 'Ain Sandel' },
    { nameAr: 'بوحشانة', nameFr: 'Bou Hachana' },
    { nameAr: 'لخزارة', nameFr: 'Khezaras' },
    { nameAr: 'بلخير', nameFr: 'Belkheir' },
    { nameAr: 'بني مزلين', nameFr: 'Beni Mezline' },
    { nameAr: 'قلعة بوصبع', nameFr: 'Guelaat Bou Sbaa' },
    { nameAr: 'وادي الشحم', nameFr: 'Oued Cheham' },
    { nameAr: 'بن جراح', nameFr: 'Bendjarah' },
  ],
  25: [
    { nameAr: 'ديدوش مراد', nameFr: 'Didouche Mourad' },
    { nameAr: 'حامة بوزيان', nameFr: 'Hamma Bouziane' },
    { nameAr: 'بني حميدان', nameFr: 'Beni Hamidane' },
    { nameAr: 'زيغود يوسف', nameFr: 'Zighoud Youcef' },
    { nameAr: 'عين السمارة', nameFr: 'Ain Smara' },
    { nameAr: 'الخروب', nameFr: 'El Khroub' },
    { nameAr: 'أولاد رحمون', nameFr: 'Ouled Rahmoun' },
    { nameAr: 'عين عبيد', nameFr: 'Ain Abid' },
    { nameAr: 'أبن باديس الهرية', nameFr: 'Ben Badis' },
    { nameAr: 'ابن زياد', nameFr: 'Ibn Ziad' },
    { nameAr: 'بوجريو مسعود', nameFr: 'Messaoud Boudjeriou' },
    { nameAr: 'قسنطينة', nameFr: 'Constantine' },
  ],
  26: [
    { nameAr: 'السواقي', nameFr: 'Souagui' },
    { nameAr: 'العزيزية', nameFr: 'El Azizia' },
    { nameAr: 'مغراوة', nameFr: 'Maghraoua' },
    { nameAr: 'ميهوب', nameFr: 'Mihoub' },
    { nameAr: 'حناشة', nameFr: 'Hannacha' },
    { nameAr: 'عوامري', nameFr: 'Ouamri' },
    { nameAr: 'وادي حربيل', nameFr: 'Oued Harbil' },
    { nameAr: 'بني سليمان', nameFr: 'Beni Slimane' },
    { nameAr: 'بوعيشون', nameFr: 'Bouaichoune' },
    { nameAr: 'أولاد بوعشرة', nameFr: 'Ouled Bouachra' },
    { nameAr: 'سي المحجوب', nameFr: 'Si Mahdjoub' },
    { nameAr: 'بوسكن', nameFr: 'Bouskene' },
    { nameAr: 'سيدي الربيع', nameFr: 'Sidi Rabie' },
    { nameAr: 'البرواقية', nameFr: 'Berrouaghia' },
    { nameAr: 'أولاد دايد', nameFr: 'Ouled Deid' },
    { nameAr: 'الربعية', nameFr: 'Rebaia' },
    { nameAr: 'مجبر', nameFr: 'Medjebar' },
    { nameAr: 'ثلاث دوائر', nameFr: 'Tletat Ed Douair' },
    { nameAr: 'الزبيرية', nameFr: 'Zoubiria' },
    { nameAr: 'العيساوية', nameFr: 'Aissaouia' },
    { nameAr: 'الحوضان', nameFr: 'El Haoudane' },
    { nameAr: 'مزغنة', nameFr: 'Mezerana' },
    { nameAr: 'تابلاط', nameFr: 'Tablat' },
    { nameAr: 'سغوان', nameFr: 'Seghouane' },
    { nameAr: 'ذراع السمار', nameFr: 'Draa Esmar' },
    { nameAr: 'المدية', nameFr: 'Medea' },
    { nameAr: 'تمسقيدة', nameFr: 'Tamesguida' },
    { nameAr: 'بن شكاو', nameFr: 'Ben Chicao' },
    { nameAr: 'الحمدانية', nameFr: 'El Hamdania' },
    { nameAr: 'وزرة', nameFr: 'Ouzera' },
    { nameAr: 'تيزي مهدي', nameFr: 'Tizi Mahdi' },
    { nameAr: 'بعطة', nameFr: 'Baata' },
    { nameAr: 'العمارية', nameFr: 'El Omaria' },
    { nameAr: 'أولاد إبراهيم', nameFr: 'Ouled Brahim' },
    { nameAr: 'بئر بن عابد', nameFr: 'Bir Ben Laabed' },
    { nameAr: 'القلب الكبير', nameFr: 'El Guelbelkebir' },
    { nameAr: 'سدراية', nameFr: 'Sedraya' },
    { nameAr: 'بوشراحيل', nameFr: 'Bouchrahil' },
    { nameAr: 'خمس جوامع', nameFr: 'Khams Djouamaa' },
    { nameAr: 'سيدي نعمان', nameFr: 'Sidi Naamane' },
    { nameAr: 'جواب', nameFr: 'Djouab' },
    { nameAr: 'سيدي زهار', nameFr: 'Sidi Zahar' },
    { nameAr: 'سيدي زيان', nameFr: 'Sidi Ziane' },
  ],
  27: [
    { nameAr: 'فرناقة', nameFr: 'Fornaka' },
    { nameAr: 'وادي الخير', nameFr: 'Oued El Kheir' },
    { nameAr: 'الحسيان (بني ياحي', nameFr: 'Hassiane' },
    { nameAr: 'حاسي ماماش', nameFr: 'Hassi Mameche' },
    { nameAr: 'مزغران', nameFr: 'Mazagran' },
    { nameAr: 'ستيدية', nameFr: 'Stidia' },
    { nameAr: 'عين تادلس', nameFr: 'Ain-Tedles' },
    { nameAr: 'سيدي بلعطار', nameFr: 'Sidi Belaattar' },
    { nameAr: 'سور', nameFr: 'Sour' },
    { nameAr: 'عين بودينار', nameFr: 'Ain-Boudinar' },
    { nameAr: 'خير الدين', nameFr: 'Kheir-Eddine' },
    { nameAr: 'صيادة', nameFr: 'Sayada' },
    { nameAr: 'سيدي علي', nameFr: 'Sidi Ali' },
    { nameAr: 'تزقايت', nameFr: 'Tazgait' },
    { nameAr: 'بن عبد المالك رمضان', nameFr: 'Benabdelmalek Ramdane' },
    { nameAr: 'مستغانم', nameFr: 'Mostaganem' },
    { nameAr: 'حجاج', nameFr: 'Hadjadj' },
    { nameAr: 'سيدي لخضر', nameFr: 'Sidi-Lakhdar' },
    { nameAr: 'عشعاشة', nameFr: 'Achaacha' },
    { nameAr: 'خضرة', nameFr: 'Khadra' },
    { nameAr: 'نكمارية', nameFr: 'Nekmaria' },
    { nameAr: 'أولاد بوغالم', nameFr: 'Ouled Boughalem' },
    { nameAr: 'بوقيراط', nameFr: 'Bouguirat' },
    { nameAr: 'صفصاف', nameFr: 'Safsaf' },
    { nameAr: 'سيرات', nameFr: 'Sirat' },
    { nameAr: 'السوافلية', nameFr: 'Souaflia' },
    { nameAr: 'عين سيدي الشريف', nameFr: 'Ain-Sidi Cherif' },
    { nameAr: 'منصورة', nameFr: 'Mansourah' },
    { nameAr: 'ماسرة', nameFr: 'Mesra' },
    { nameAr: 'الطواهرية', nameFr: 'Touahria' },
    { nameAr: 'عين نويسي', nameFr: 'Ain-Nouissy' },
    { nameAr: 'أولاد مع الله', nameFr: 'Ouled-Maalah' },
  ],
  28: [
    { nameAr: 'شلال', nameFr: 'Chellal' },
    { nameAr: 'أولاد ماضي', nameFr: 'Ouled Madhi' },
    { nameAr: 'خطوطي سد الجير', nameFr: 'Khettouti Sed-El-Jir' },
    { nameAr: 'بلعايبة', nameFr: 'Belaiba' },
    { nameAr: 'برهوم', nameFr: 'Berhoum' },
    { nameAr: 'دهاهنة', nameFr: 'Dehahna' },
    { nameAr: 'مقرة', nameFr: 'Magra' },
    { nameAr: 'بني يلمان', nameFr: 'Beni Ilmane' },
    { nameAr: 'بوطي السايح', nameFr: 'Bouti Sayeh' },
    { nameAr: 'سيدي عيسى', nameFr: 'Sidi Aissa' },
    { nameAr: 'عين الحجل', nameFr: 'Ain El Hadjel' },
    { nameAr: 'جبل مساعد', nameFr: 'Djebel Messaad' },
    { nameAr: 'المسيلة', nameFr: 'M\'sila' },
    { nameAr: 'حمام الضلعة', nameFr: 'Hammam Dalaa' },
    { nameAr: 'ونوغة', nameFr: 'Ouanougha' },
    { nameAr: 'أولاد منصور', nameFr: 'Ouled Mansour' },
    { nameAr: 'تارمونت', nameFr: 'Tarmount' },
    { nameAr: 'أولاد دراج', nameFr: 'Ouled Derradj' },
    { nameAr: 'السوامع', nameFr: 'Souamaa' },
    { nameAr: 'الحوامد', nameFr: 'El Houamed' },
    { nameAr: 'خبانة', nameFr: 'Khoubana' },
    { nameAr: 'مسيف', nameFr: 'M\'cif' },
    { nameAr: 'عين الخضراء', nameFr: 'Ain Khadra' },
    { nameAr: 'أولاد عدي لقبالة', nameFr: 'Ouled Addi Guebala' },
  ],
  29: [
    { nameAr: 'وادي الأبطال', nameFr: 'Oued El Abtal' },
    { nameAr: 'سيدي عبد المومن', nameFr: 'Sidi Abdelmoumene' },
    { nameAr: 'سجرارة', nameFr: 'Sedjerara' },
    { nameAr: 'المحمدية', nameFr: 'Mohammadia' },
    { nameAr: 'تيغنيف', nameFr: 'Tighennif' },
    { nameAr: 'مقطع الدوز', nameFr: 'Mocta-Douz' },
    { nameAr: 'فراقيق', nameFr: 'Ferraguig' },
    { nameAr: 'الغمري', nameFr: 'El Ghomri' },
    { nameAr: 'زهانة', nameFr: 'Zahana' },
    { nameAr: 'القعدة', nameFr: 'El Gaada' },
    { nameAr: 'رأس عين عميروش', nameFr: 'Ras El Ain Amirouche' },
    { nameAr: 'عقاز', nameFr: 'Oggaz' },
    { nameAr: 'العلايمية', nameFr: 'Alaimia' },
    { nameAr: 'سيق', nameFr: 'Sig' },
    { nameAr: 'الشرفاء', nameFr: 'Chorfa' },
    { nameAr: 'بوهني', nameFr: 'Bou Henni' },
    { nameAr: 'المأمونية', nameFr: 'El Mamounia' },
    { nameAr: 'القطنة', nameFr: 'El Gueitena' },
    { nameAr: 'عين فارس', nameFr: 'Ain Fares' },
    { nameAr: 'غروس', nameFr: 'Gharrous' },
    { nameAr: 'بنيان', nameFr: 'Benian' },
    { nameAr: 'عوف', nameFr: 'Aouf' },
    { nameAr: 'قرجوم', nameFr: 'Guerdjoum' },
    { nameAr: 'عين أفرص', nameFr: 'Ain Frass' },
    { nameAr: 'عين فكان', nameFr: 'Ain Fekan' },
    { nameAr: 'خلوية', nameFr: 'Khalouia' },
    { nameAr: 'المنور', nameFr: 'El Menaouer' },
    { nameAr: 'البرج', nameFr: 'El Bordj' },
    { nameAr: 'سيدي بوسعيد', nameFr: 'Sidi Boussaid' },
    { nameAr: 'المطمور', nameFr: 'Matemore' },
    { nameAr: 'سيدي قادة', nameFr: 'Sidi Kada' },
    { nameAr: 'ماقضة', nameFr: 'Makhda' },
    { nameAr: 'معسكر', nameFr: 'Mascara' },
    { nameAr: 'بوحنيفية', nameFr: 'Bouhanifia' },
    { nameAr: 'غريس', nameFr: 'Ghriss' },
    { nameAr: 'حسين', nameFr: 'Hacine' },
    { nameAr: 'القرط', nameFr: 'El Keurt' },
    { nameAr: 'فروحة', nameFr: 'Froha' },
    { nameAr: 'تيزي', nameFr: 'Tizi' },
    { nameAr: 'السهايلية', nameFr: 'Sehailia' },
    { nameAr: 'ماوسة', nameFr: 'Maoussa' },
    { nameAr: 'سيدي عبد الجبار', nameFr: 'Sidi Abdeldjebar' },
    { nameAr: 'الحشم', nameFr: 'El Hachem' },
    { nameAr: 'نسمط', nameFr: 'Nesmot' },
    { nameAr: 'زلامطة', nameFr: 'Zelamta' },
    { nameAr: 'عين فراح', nameFr: 'Ain Ferah' },
    { nameAr: 'وادي التاغية', nameFr: 'Oued Taria' },
  ],
  30: [
    { nameAr: 'ورقلة', nameFr: 'Ouargla' },
    { nameAr: 'حاسي مسعود', nameFr: 'Hassi Messaoud' },
    { nameAr: 'عين البيضاء', nameFr: 'Ain Beida' },
    { nameAr: 'حاسي بن عبد الله', nameFr: 'Hassi Ben Abdellah' },
    { nameAr: 'سيدي خويلد', nameFr: 'Sidi Khouiled' },
    { nameAr: 'البرمة', nameFr: 'El Borma' },
    { nameAr: 'الرويسات', nameFr: 'Rouissat' },
    { nameAr: 'انقوسة', nameFr: 'N\'goussa' },
  ],
  31: [
    { nameAr: 'سيدي الشحمي', nameFr: 'Sidi Chami' },
    { nameAr: 'حاسي مفسوخ', nameFr: 'Hassi Mefsoukh' },
    { nameAr: 'بئر الجير', nameFr: 'Bir El Djir' },
    { nameAr: 'حاسي بن عقبة', nameFr: 'Hassi Ben Okba' },
    { nameAr: 'قديل', nameFr: 'Gdyel' },
    { nameAr: 'حاسي بونيف', nameFr: 'Hassi Bounif' },
    { nameAr: 'الكرمة', nameFr: 'El Kerma' },
    { nameAr: 'السانية', nameFr: 'Es Senia' },
    { nameAr: 'بن فريحة', nameFr: 'Ben Freha' },
    { nameAr: 'أرزيو', nameFr: 'Arzew' },
    { nameAr: 'سيدي بن يبقى', nameFr: 'Sidi Ben Yebka' },
    { nameAr: 'عين البية', nameFr: 'Ain Biya' },
    { nameAr: 'بطيوة', nameFr: 'Bethioua' },
    { nameAr: 'مرسى الحجاج', nameFr: 'Marsat El Hadjadj' },
    { nameAr: 'عين الترك', nameFr: 'Ain Turk' },
    { nameAr: 'وهران', nameFr: 'Oran' },
    { nameAr: 'العنصر', nameFr: 'El Ancor' },
    { nameAr: 'المرسى الكبير', nameFr: 'Mers El Kebir' },
    { nameAr: 'بوفاتيس', nameFr: 'Boufatis' },
    { nameAr: 'البراية', nameFr: 'El Braya' },
    { nameAr: 'وادي تليلات', nameFr: 'Oued Tlelat' },
    { nameAr: 'عين الكرمة', nameFr: 'Ain Kerma' },
    { nameAr: 'بوتليليس', nameFr: 'Boutlelis' },
    { nameAr: 'مسرغين', nameFr: 'Messerghin' },
    { nameAr: 'بوسفر', nameFr: 'Bousfer' },
    { nameAr: 'طفراوي', nameFr: 'Tafraoui' },
  ],
  32: [
    { nameAr: 'عين العراك', nameFr: 'Ain El Orak' },
    { nameAr: 'كراكدة', nameFr: 'Krakda' },
    { nameAr: 'سيدي سليمان', nameFr: 'Sidi Slimane' },
    { nameAr: 'سيدي عامر', nameFr: 'Sidi Ameur' },
    { nameAr: 'بوعلام', nameFr: 'Boualem' },
    { nameAr: 'البنود', nameFr: 'El Bnoud' },
    { nameAr: 'بوقطب', nameFr: 'Bougtoub' },
    { nameAr: 'الخيثر', nameFr: 'El Kheiter' },
    { nameAr: 'توسمولين', nameFr: 'Tousmouline' },
    { nameAr: 'سيدي طيفور', nameFr: 'Sidi Tiffour' },
    { nameAr: 'ستيتن', nameFr: 'Stitten' },
    { nameAr: 'البيض', nameFr: 'El Bayadh' },
    { nameAr: 'رقاصة', nameFr: 'Rogassa' },
    { nameAr: 'المحرة', nameFr: 'El Mehara' },
    { nameAr: 'الكاف الأحمر', nameFr: 'Kef El Ahmar' },
  ],
  33: [
    { nameAr: 'برج عمر إدريس', nameFr: 'Bordj Omar Driss' },
    { nameAr: 'دبداب', nameFr: 'Debdeb' },
    { nameAr: 'إن أمناس', nameFr: 'In Amenas' },
    { nameAr: 'إيليزي', nameFr: 'Illizi' },
  ],
  34: [
    { nameAr: 'الحمادية', nameFr: 'Elhammadia' },
    { nameAr: 'أولاد سيدي ابراهيم', nameFr: 'Ouled Sidi-Brahim' },
    { nameAr: 'عين تاغروت', nameFr: 'Ain Taghrout' },
    { nameAr: 'تيكستار', nameFr: 'Tixter' },
    { nameAr: 'بليمور', nameFr: 'Belimour' },
    { nameAr: 'العناصر', nameFr: 'El Annasseur' },
    { nameAr: 'غيلاسة', nameFr: 'Ghailasa' },
    { nameAr: 'تقلعيت', nameFr: 'Taglait' },
    { nameAr: 'برج الغدير', nameFr: 'Bordj Ghedir' },
    { nameAr: 'العش', nameFr: 'El Euch' },
    { nameAr: 'سيدي أمبارك', nameFr: 'Sidi-Embarek' },
    { nameAr: 'خليل', nameFr: 'Khelil' },
    { nameAr: 'بئر قاصد علي', nameFr: 'Bir Kasdali' },
    { nameAr: 'تفرق', nameFr: 'Tefreg' },
    { nameAr: 'الماين', nameFr: 'El Main' },
    { nameAr: 'جعافرة', nameFr: 'Djaafra' },
    { nameAr: 'القلة', nameFr: 'Colla' },
    { nameAr: 'ثنية النصر', nameFr: 'Teniet En Nasr' },
    { nameAr: 'المهير', nameFr: 'El M\'hir' },
    { nameAr: 'القصور', nameFr: 'Ksour' },
    { nameAr: 'المنصورة', nameFr: 'Mansoura' },
    { nameAr: 'حرازة', nameFr: 'Haraza' },
    { nameAr: 'الرابطة', nameFr: 'Rabta' },
    { nameAr: 'الياشير', nameFr: 'El Achir' },
    { nameAr: 'حسناوة', nameFr: 'Hasnaoua' },
    { nameAr: 'مجانة', nameFr: 'Medjana' },
    { nameAr: 'عين تسرة', nameFr: 'Ain Tesra' },
    { nameAr: 'أولاد أبراهم', nameFr: 'Ouled Brahem' },
    { nameAr: 'رأس الوادي', nameFr: 'Ras El Oued' },
    { nameAr: 'برج زمورة', nameFr: 'Bordj Zemmoura' },
    { nameAr: 'أولاد دحمان', nameFr: 'Ouled Dahmane' },
    { nameAr: 'تسامرت', nameFr: 'Tassamert' },
    { nameAr: 'برج بوعريرج', nameFr: 'B. B. Arreridj' },
    { nameAr: 'بن داود', nameFr: 'Ben Daoud' },
  ],
  35: [
    { nameAr: 'الخروبة', nameFr: 'El Kharrouba' },
    { nameAr: 'دلس', nameFr: 'Dellys' },
    { nameAr: 'بن شود', nameFr: 'Ben Choud' },
    { nameAr: 'أعفير', nameFr: 'Afir' },
    { nameAr: 'الثنية', nameFr: 'Thenia' },
    { nameAr: 'بني عمران', nameFr: 'Beni Amrane' },
    { nameAr: 'خميس الخشنة', nameFr: 'Khemis El Khechna' },
    { nameAr: 'عمال', nameFr: 'Ammal' },
    { nameAr: 'تيمزريت', nameFr: 'Timezrit' },
    { nameAr: 'زموري', nameFr: 'Zemmouri' },
    { nameAr: 'الاربعطاش', nameFr: 'Larbatache' },
    { nameAr: 'يسر', nameFr: 'Isser' },
    { nameAr: 'شعبة العامر', nameFr: 'Chabet El Ameur' },
    { nameAr: 'أولاد عيسى', nameFr: 'Ouled Aissa' },
    { nameAr: 'الناصرية', nameFr: 'Naciria' },
    { nameAr: 'بوزقزة قدارة', nameFr: 'Bouzegza Keddara' },
    { nameAr: 'سوق الحد', nameFr: 'Souk El Had' },
    { nameAr: 'سيدي داود', nameFr: 'Sidi Daoud' },
    { nameAr: 'بغلية', nameFr: 'Baghlia' },
    { nameAr: 'لقاطة', nameFr: 'Leghata' },
    { nameAr: 'جنات', nameFr: 'Djinet' },
    { nameAr: 'تيجلابين', nameFr: 'Tidjelabine' },
    { nameAr: 'سي مصطفى', nameFr: 'Si Mustapha' },
    { nameAr: 'أولاد هداج', nameFr: 'Ouled Hedadj' },
    { nameAr: 'أولاد موسى', nameFr: 'Ouled Moussa' },
    { nameAr: 'بومرداس', nameFr: 'Boumerdes' },
    { nameAr: 'قورصو', nameFr: 'Corso' },
    { nameAr: 'برج منايل', nameFr: 'Bordj Menaiel' },
    { nameAr: 'بودواو', nameFr: 'Boudouaou' },
    { nameAr: 'بودواو البحري', nameFr: 'Boudouaou El Bahri' },
    { nameAr: 'تاورقة', nameFr: 'Taourga' },
    { nameAr: 'حمادي', nameFr: 'Hammedi' },
  ],
  36: [
    { nameAr: 'عين العسل', nameFr: 'Ain El Assel' },
    { nameAr: 'بوقوس', nameFr: 'Bougous' },
    { nameAr: 'الطارف', nameFr: 'El Tarf' },
    { nameAr: 'الزيتونة', nameFr: 'Zitouna' },
    { nameAr: 'البسباس', nameFr: 'Besbes' },
    { nameAr: 'عين الكرمة', nameFr: 'Ain Kerma' },
    { nameAr: 'بوحجار', nameFr: 'Bouhadjar' },
    { nameAr: 'حمام بني صالح', nameFr: 'Hammam Beni Salah' },
    { nameAr: 'وادي الزيتون', nameFr: 'Oued Zitoun' },
    { nameAr: 'بن مهيدي', nameFr: 'Ben M Hidi' },
    { nameAr: 'بريحان', nameFr: 'Berrihane' },
    { nameAr: 'شبيطة مختار', nameFr: 'Chebaita Mokhtar' },
    { nameAr: 'الشط', nameFr: 'Echatt' },
    { nameAr: 'العيون', nameFr: 'El Aioun' },
    { nameAr: 'القالة', nameFr: 'El Kala' },
    { nameAr: 'السوارخ', nameFr: 'Souarekh' },
    { nameAr: 'زريزر', nameFr: 'Zerizer' },
    { nameAr: 'بوثلجة', nameFr: 'Bouteldja' },
    { nameAr: 'الشافية', nameFr: 'Chefia' },
    { nameAr: 'بحيرة الطيور', nameFr: 'Lac Des Oiseaux' },
    { nameAr: 'شحاني', nameFr: 'Chihani' },
    { nameAr: 'رمل السوق', nameFr: 'Raml Souk' },
    { nameAr: 'عصفور', nameFr: 'Asfour' },
    { nameAr: 'الذرعـان', nameFr: 'Drean' },
  ],
  37: [
    { nameAr: 'تندوف', nameFr: 'Tindouf' },
    { nameAr: 'أم العسل', nameFr: 'Oum El Assel' },
  ],
  38: [
    { nameAr: 'خميستي', nameFr: 'Khemisti' },
    { nameAr: 'ثنية الاحد', nameFr: 'Theniet El Had' },
    { nameAr: 'أولاد بسام', nameFr: 'Ouled Bessam' },
    { nameAr: 'سيدي بوتوشنت', nameFr: 'Sidi Boutouchent' },
    { nameAr: 'تيسمسيلت', nameFr: 'Tissemsilt' },
    { nameAr: 'سيدي العنتري', nameFr: 'Sidi Lantri' },
    { nameAr: 'بني شعيب', nameFr: 'Beni Chaib' },
    { nameAr: 'بني لحسن', nameFr: 'Beni Lahcene' },
    { nameAr: 'سيدي عابد', nameFr: 'Sidi Abed' },
    { nameAr: 'سيدي سليمان', nameFr: 'Sidi Slimane' },
    { nameAr: 'بوقائد', nameFr: 'Boucaid' },
    { nameAr: 'الأربعاء', nameFr: 'Larbaa' },
    { nameAr: 'الأزهرية', nameFr: 'Lazharia' },
    { nameAr: 'لرجام', nameFr: 'Lardjem' },
    { nameAr: 'الملعب', nameFr: 'Melaab' },
    { nameAr: 'العيون', nameFr: 'Layoune' },
    { nameAr: 'تملاحت', nameFr: 'Tamellahet' },
    { nameAr: 'اليوسفية', nameFr: 'Youssoufia' },
    { nameAr: 'برج الأمير عبد القادر', nameFr: 'Bordj El Emir Abdelkader' },
    { nameAr: 'عماري', nameFr: 'Ammari' },
    { nameAr: 'المعاصم', nameFr: 'Maacem' },
    { nameAr: 'برج بونعامة', nameFr: 'Bordj Bounaama' },
  ],
  39: [
    { nameAr: 'دوار الماء', nameFr: 'Douar El Maa' },
    { nameAr: 'العقلة', nameFr: 'El Ogla' },
    { nameAr: 'المقرن', nameFr: 'Magrane' },
    { nameAr: 'سيدي عون', nameFr: 'Sidi Aoun' },
    { nameAr: 'اميه وانسة', nameFr: 'Mih Ouansa' },
    { nameAr: 'كوينين', nameFr: 'Kouinine' },
    { nameAr: 'البياضة', nameFr: 'Bayadha' },
    { nameAr: 'النخلة', nameFr: 'Nakhla' },
    { nameAr: 'الرباح', nameFr: 'Robbah' },
    { nameAr: 'قمار', nameFr: 'Guemar' },
    { nameAr: 'بن  قشة', nameFr: 'Ben Guecha' },
    { nameAr: 'ورماس', nameFr: 'Ourmes' },
    { nameAr: 'تغزوت', nameFr: 'Taghzout' },
    { nameAr: 'الحمراية', nameFr: 'Hamraia' },
    { nameAr: 'الرقيبة', nameFr: 'Reguiba' },
    { nameAr: 'الدبيلة', nameFr: 'Debila' },
    { nameAr: 'حساني عبد الكريم', nameFr: 'Hassani Abdelkrim' },
    { nameAr: 'حاسي خليفة', nameFr: 'Hassi Khalifa' },
    { nameAr: 'الطريفاوي', nameFr: 'Trifaoui' },
    { nameAr: 'الطالب العربي', nameFr: 'Taleb Larbi' },
    { nameAr: 'وادي العلندة', nameFr: 'Oued El Alenda' },
    { nameAr: 'الوادي', nameFr: 'El-Oued' },
  ],
  40: [
    { nameAr: 'خيران', nameFr: 'Khirane' },
    { nameAr: 'بابار', nameFr: 'Babar' },
    { nameAr: 'المحمل', nameFr: 'El Mahmal' },
    { nameAr: 'أولاد رشاش', nameFr: 'Ouled Rechache' },
    { nameAr: 'جلال', nameFr: 'Djellal' },
    { nameAr: 'يابوس', nameFr: 'Yabous' },
    { nameAr: 'خنشلة', nameFr: 'Khenchela' },
    { nameAr: 'قايس', nameFr: 'Kais' },
    { nameAr: 'شلية', nameFr: 'Chelia' },
    { nameAr: 'الرميلة', nameFr: 'Remila' },
    { nameAr: 'تاوزيانت', nameFr: 'Taouzianat' },
    { nameAr: 'بغاي', nameFr: 'Baghai' },
    { nameAr: 'الحامة', nameFr: 'El Hamma' },
    { nameAr: 'انسيغة', nameFr: 'Ensigha' },
    { nameAr: 'طامزة', nameFr: 'Tamza' },
    { nameAr: 'عين الطويلة', nameFr: 'Ain Touila' },
    { nameAr: 'متوسة', nameFr: 'M\'toussa' },
    { nameAr: 'بوحمامة', nameFr: 'Bouhmama' },
    { nameAr: 'الولجة', nameFr: 'El Oueldja' },
    { nameAr: 'مصارة', nameFr: 'M\'sara' },
    { nameAr: 'ششار', nameFr: 'Chechar' },
  ],
  41: [
    { nameAr: 'سوق أهراس', nameFr: 'Souk Ahras' },
    { nameAr: 'عين سلطان', nameFr: 'Ain Soltane' },
    { nameAr: 'سدراتة', nameFr: 'Sedrata' },
    { nameAr: 'الحنانشة', nameFr: 'Hanencha' },
    { nameAr: 'المشروحة', nameFr: 'Machroha' },
    { nameAr: 'عين الزانة', nameFr: 'Ain Zana' },
    { nameAr: 'أولاد إدريس', nameFr: 'Ouled Driss' },
    { nameAr: 'ترقالت', nameFr: 'Terraguelt' },
    { nameAr: 'أم العظايم', nameFr: 'Oum El Adhaim' },
    { nameAr: 'وادي الكبريت', nameFr: 'Oued Kebrit' },
    { nameAr: 'تيفاش', nameFr: 'Tiffech' },
    { nameAr: 'الراقوبة', nameFr: 'Ragouba' },
    { nameAr: 'الدريعة', nameFr: 'Drea' },
    { nameAr: 'تاورة', nameFr: 'Taoura' },
    { nameAr: 'الزعرورية', nameFr: 'Zaarouria' },
    { nameAr: 'الحدادة', nameFr: 'Haddada' },
    { nameAr: 'الخضارة', nameFr: 'Khedara' },
    { nameAr: 'أولاد مومن', nameFr: 'Ouled Moumen' },
    { nameAr: 'المراهنة', nameFr: 'Merahna' },
    { nameAr: 'ويلان', nameFr: 'Ouillen' },
    { nameAr: 'سيدي فرج', nameFr: 'Sidi Fredj' },
    { nameAr: 'بئر بوحوش', nameFr: 'Bir Bouhouche' },
    { nameAr: 'سافل الويدان', nameFr: 'Safel El Ouiden' },
    { nameAr: 'خميسة', nameFr: 'Khemissa' },
    { nameAr: 'مداوروش', nameFr: 'M\'daourouche' },
    { nameAr: 'الزوابي', nameFr: 'Zouabi' },
  ],
  42: [
    { nameAr: 'حجوط', nameFr: 'Hadjout' },
    { nameAr: 'مراد', nameFr: 'Merad' },
    { nameAr: 'مناصر', nameFr: 'Menaceur' },
    { nameAr: 'أغبال', nameFr: 'Aghbal' },
    { nameAr: 'الناظور', nameFr: 'Nador' },
    { nameAr: 'سيدي عامر', nameFr: 'Sidi-Amar' },
    { nameAr: 'قوراية', nameFr: 'Gouraya' },
    { nameAr: 'مسلمون', nameFr: 'Messelmoun' },
    { nameAr: 'شرشال', nameFr: 'Cherchell' },
    { nameAr: 'حجرة النص', nameFr: 'Hadjret Ennous' },
    { nameAr: 'سيدي غيلاس', nameFr: 'Sidi Ghiles' },
    { nameAr: 'الداموس', nameFr: 'Damous' },
    { nameAr: 'الأرهاط', nameFr: 'Larhat' },
    { nameAr: 'فوكة', nameFr: 'Fouka' },
    { nameAr: 'عين تاقورايت', nameFr: 'Ain Tagourait' },
    { nameAr: 'بوهارون', nameFr: 'Bou Haroun' },
    { nameAr: 'بواسماعيل', nameFr: 'Bou Ismail' },
    { nameAr: 'خميستي', nameFr: 'Khemisti' },
    { nameAr: 'أحمر العين', nameFr: 'Ahmer El Ain' },
    { nameAr: 'بورقيقة', nameFr: 'Bourkika' },
    { nameAr: 'دواودة', nameFr: 'Douaouda' },
    { nameAr: 'سيدي راشد', nameFr: 'Sidi Rached' },
    { nameAr: 'الحطاطبة', nameFr: 'Attatba' },
    { nameAr: 'الشعيبة', nameFr: 'Chaiba' },
    { nameAr: 'القليعة', nameFr: 'Kolea' },
    { nameAr: 'سيدي سميان', nameFr: 'Sidi Semiane' },
    { nameAr: 'تيبازة', nameFr: 'Tipaza' },
    { nameAr: 'بني ميلك', nameFr: 'Beni Mileuk' },
  ],
  43: [
    { nameAr: 'مشيرة', nameFr: 'El Mechira' },
    { nameAr: 'العياضي برباس', nameFr: 'El Ayadi Barbes' },
    { nameAr: ' عين البيضاء أحريش', nameFr: 'Ain Beida Harriche' },
    { nameAr: 'تسالة لمطاعي', nameFr: 'Tassala Lematai' },
    { nameAr: 'ترعي باينان', nameFr: 'Terrai Bainen' },
    { nameAr: 'اعميرة اراس', nameFr: 'Amira Arres' },
    { nameAr: 'تسدان حدادة', nameFr: 'Tassadane Haddada' },
    { nameAr: 'مينار زارزة', nameFr: 'Minar Zarza' },
    { nameAr: 'سيدي مروان', nameFr: 'Sidi Merouane' },
    { nameAr: 'الشيقارة', nameFr: 'Chigara' },
    { nameAr: 'حمالة', nameFr: 'Hamala' },
    { nameAr: 'القرارم قوقة', nameFr: 'Grarem Gouga' },
    { nameAr: 'تيبرقنت', nameFr: 'Tiberguent' },
    { nameAr: 'الرواشد', nameFr: 'Rouached' },
    { nameAr: 'دراحي بوصلاح', nameFr: 'Derrahi Bousselah' },
    { nameAr: 'زغاية', nameFr: 'Zeghaia' },
    { nameAr: 'وادي النجاء', nameFr: 'Oued Endja' },
    { nameAr: 'أحمد راشدي', nameFr: 'Ahmed Rachedi' },
    { nameAr: 'تاجنانت', nameFr: 'Tadjenanet' },
    { nameAr: 'عين الملوك', nameFr: 'Ain Mellouk' },
    { nameAr: 'أولاد اخلوف', nameFr: 'Ouled Khalouf' },
    { nameAr: 'بن يحي عبد الرحمن', nameFr: 'Benyahia Abderrahmane' },
    { nameAr: 'التلاغمة', nameFr: 'Teleghma' },
    { nameAr: 'وادي سقان', nameFr: 'Oued Seguen' },
    { nameAr: 'وادي العثمانية', nameFr: 'Oued Athmenia' },
    { nameAr: 'عين التين', nameFr: 'Ain Tine' },
    { nameAr: 'شلغوم العيد', nameFr: 'Chelghoum Laid' },
    { nameAr: 'يحي بني قشة', nameFr: 'Yahia Beniguecha' },
    { nameAr: 'فرجيوة', nameFr: 'Ferdjioua' },
    { nameAr: 'سيدي خليفة', nameFr: 'Sidi Khelifa' },
    { nameAr: 'ميلة', nameFr: 'Mila' },
    { nameAr: 'بوحاتم', nameFr: 'Bouhatem' },
  ],
  44: [
    { nameAr: 'خميس مليانة', nameFr: 'Khemis-Miliana' },
    { nameAr: 'سيدي الأخضر', nameFr: 'Sidi-Lakhdar' },
    { nameAr: 'عين البنيان', nameFr: 'Ain-Benian' },
    { nameAr: 'عين التركي', nameFr: 'Ain-Torki' },
    { nameAr: 'حمام ريغة', nameFr: 'Hammam-Righa' },
    { nameAr: 'بوراشد', nameFr: 'Bourached' },
    { nameAr: 'الحسينية', nameFr: 'Hoceinia' },
    { nameAr: 'جليدة', nameFr: 'Djelida' },
    { nameAr: 'عريب', nameFr: 'Arib' },
    { nameAr: 'جمعة أولاد الشيخ', nameFr: 'Djemaa Ouled Cheikh' },
    { nameAr: 'العامرة', nameFr: 'El-Amra' },
    { nameAr: 'العطاف', nameFr: 'El-Attaf' },
    { nameAr: 'تبركانين', nameFr: 'Tiberkanine' },
    { nameAr: 'عين بويحيى', nameFr: 'Ain-Bouyahia' },
    { nameAr: 'العبادية', nameFr: 'El-Abadia' },
    { nameAr: 'تاشتة زقاغة', nameFr: 'Tacheta Zegagha' },
    { nameAr: 'بربوش', nameFr: 'Birbouche' },
    { nameAr: 'جندل', nameFr: 'Djendel' },
    { nameAr: 'بن علال', nameFr: 'Ben Allal' },
    { nameAr: 'وادي الشرفاء', nameFr: 'Oued Chorfa' },
    { nameAr: 'بومدفع', nameFr: 'Boumedfaa' },
    { nameAr: 'عين الاشياخ', nameFr: 'Ain-Lechiakh' },
    { nameAr: 'عين السلطان', nameFr: 'Ain-Soltane' },
    { nameAr: 'واد الجمعة', nameFr: 'Oued Djemaa' },
    { nameAr: 'الماين', nameFr: 'El-Maine' },
    { nameAr: 'الروينة', nameFr: 'Rouina' },
    { nameAr: 'زدين', nameFr: 'Zeddine' },
    { nameAr: 'بئر ولد خليفة', nameFr: 'Bir-Ould-Khelifa' },
    { nameAr: 'برج الأمير خالد', nameFr: 'Bordj-Emir-Khaled' },
    { nameAr: 'طارق بن زياد', nameFr: 'Tarik-Ibn-Ziad' },
    { nameAr: 'بطحية', nameFr: 'Bathia' },
    { nameAr: 'بلعاص', nameFr: 'Belaas' },
    { nameAr: 'الحسانية', nameFr: 'Hassania' },
    { nameAr: 'عين الدفلى', nameFr: 'Ain-Defla' },
    { nameAr: 'مليانة', nameFr: 'Miliana' },
    { nameAr: 'المخاطرية', nameFr: 'Mekhatria' },
  ],
  45: [
    { nameAr: 'تيوت', nameFr: 'Tiout' },
    { nameAr: 'مغرار', nameFr: 'Moghrar' },
    { nameAr: 'عسلة', nameFr: 'Asla' },
    { nameAr: 'القصدير', nameFr: 'Kasdir' },
    { nameAr: 'مكمن بن عمار', nameFr: 'Makmen Ben Amar' },
    { nameAr: 'عين الصفراء', nameFr: 'Ain Sefra' },
    { nameAr: 'المشرية', nameFr: 'Mecheria' },
    { nameAr: 'البيوض', nameFr: 'El Biodh' },
    { nameAr: 'عين بن خليل', nameFr: 'Ain Ben Khelil' },
    { nameAr: 'النعامة', nameFr: 'Naama' },
    { nameAr: 'جنين بورزق', nameFr: 'Djenienne Bourezg' },
    { nameAr: 'سفيسيفة', nameFr: 'Sfissifa' },
  ],
  46: [
    { nameAr: 'سيدي بومدين', nameFr: 'Sidi Boumediene' },
    { nameAr: 'تامزورة', nameFr: 'Tamzoura' },
    { nameAr: 'شعبة اللحم', nameFr: 'Chaabat El Ham' },
    { nameAr: 'المالح', nameFr: 'El Maleh' },
    { nameAr: 'أولاد الكيحل', nameFr: 'Ouled Kihal' },
    { nameAr: 'شنتوف', nameFr: 'Chentouf' },
    { nameAr: 'تارقة', nameFr: 'Terga' },
    { nameAr: 'وادي الصباح', nameFr: 'Oued Sebbah' },
    { nameAr: 'العامرية', nameFr: 'El Amria' },
    { nameAr: 'حاسي الغلة', nameFr: 'Hassi El Ghella' },
    { nameAr: 'أولاد بوجمعة', nameFr: 'Ouled Boudjemaa' },
    { nameAr: 'أغلال', nameFr: 'Aghlal' },
    { nameAr: 'عين الكيحل', nameFr: 'Ain Kihal' },
    { nameAr: 'عين الطلبة', nameFr: 'Ain Tolba' },
    { nameAr: 'عقب الليل', nameFr: 'Aoubellil' },
    { nameAr: 'بني صاف', nameFr: 'Beni Saf' },
    { nameAr: 'الحساسنة', nameFr: 'Hassasna' },
    { nameAr: 'الأمير عبد القادر', nameFr: 'Emir Abdelkader' },
    { nameAr: 'سيدي صافي', nameFr: 'Sidi Safi' },
    { nameAr: 'ولهاصة الغرابة', nameFr: 'Oulhaca El Gheraba' },
    { nameAr: 'سيدي ورياش', nameFr: 'Sidi Ouriache' },
    { nameAr: 'عين الأربعاء', nameFr: 'Ain El Arbaa' },
    { nameAr: 'المساعيد', nameFr: 'El Messaid' },
    { nameAr: 'وادي برقش', nameFr: 'Oued Berkeche' },
    { nameAr: 'سيدي بن عدة', nameFr: 'Sidi Ben Adda' },
    { nameAr: 'عين تموشنت', nameFr: 'Ain Temouchent' },
    { nameAr: 'بوزجار', nameFr: 'Bouzedjar' },
    { nameAr: 'حمام بوحجر', nameFr: 'Hammam Bou Hadjar' },
  ],
  47: [
    { nameAr: 'ضاية بن ضحوة', nameFr: 'Dhayet Bendhahoua' },
    { nameAr: 'المنصورة', nameFr: 'Mansoura' },
    { nameAr: 'العطف', nameFr: 'El Atteuf' },
    { nameAr: 'بونورة', nameFr: 'Bounoura' },
    { nameAr: 'زلفانة', nameFr: 'Zelfana' },
    { nameAr: 'القرارة', nameFr: 'El Guerrara' },
    { nameAr: 'سبسب', nameFr: 'Sebseb' },
    { nameAr: 'متليلي', nameFr: 'Metlili' },
    { nameAr: 'بريان', nameFr: 'Berriane' },
    { nameAr: 'غرداية', nameFr: 'Ghardaia' },
  ],
  48: [
    { nameAr: 'القطار', nameFr: 'El-Guettar' },
    { nameAr: 'أولاد يعيش', nameFr: 'Ouled Aiche' },
    { nameAr: 'بني درقن', nameFr: 'Beni Dergoun' },
    { nameAr: 'دار بن عبد الله', nameFr: 'Dar Ben Abdelah' },
    { nameAr: 'زمورة', nameFr: 'Zemmoura' },
    { nameAr: 'جديوية', nameFr: 'Djidiouia' },
    { nameAr: 'حمري', nameFr: 'Hamri' },
    { nameAr: 'بلعسل بوزقزة', nameFr: 'Belaassel Bouzagza' },
    { nameAr: 'المطمر', nameFr: 'El-Matmar' },
    { nameAr: 'سيدي  خطاب', nameFr: 'Sidi Khettab' },
    { nameAr: 'سيدي امحمد بن عودة', nameFr: 'Sidi M\'hamed Benaouda' },
    { nameAr: 'عين طارق', nameFr: 'Ain-Tarek' },
    { nameAr: 'حد الشكالة', nameFr: 'Had Echkalla' },
    { nameAr: 'الولجة', nameFr: 'El Ouldja' },
    { nameAr: 'مازونة', nameFr: 'Mazouna' },
    { nameAr: 'عين الرحمة', nameFr: 'Ain Rahma' },
    { nameAr: 'القلعة', nameFr: 'Kalaa' },
    { nameAr: 'سيدي سعادة', nameFr: 'Sidi Saada' },
    { nameAr: 'يلل', nameFr: 'Yellel' },
    { nameAr: 'سوق الحد', nameFr: 'Souk El Had' },
    { nameAr: 'منداس', nameFr: 'Mendes' },
    { nameAr: 'وادي السلام', nameFr: 'Oued Essalem' },
    { nameAr: 'سيدي لزرق', nameFr: 'Sidi Lazreg' },
    { nameAr: 'عمي موسى', nameFr: 'Ammi Moussa' },
    { nameAr: 'واريزان', nameFr: 'Ouarizane' },
    { nameAr: 'مرجة سيدي عابد', nameFr: 'Merdja Sidi Abed' },
    { nameAr: 'أولاد سيدي الميهوب', nameFr: 'Ouled Sidi Mihoub' },
    { nameAr: 'بن داود', nameFr: 'Bendaoud' },
    { nameAr: 'وادي رهيو', nameFr: 'Oued-Rhiou' },
    { nameAr: 'الحاسي', nameFr: 'El Hassi' },
    { nameAr: 'سيدي أمحمد بن علي', nameFr: 'Sidi M\'hamed Benali' },
    { nameAr: 'مديونة', nameFr: 'Mediouna' },
    { nameAr: 'بني زنطيس', nameFr: 'Beni Zentis' },
    { nameAr: 'وادي الجمعة', nameFr: 'Oued El Djemaa' },
    { nameAr: 'لحلاف', nameFr: 'Lahlef' },
    { nameAr: 'غليزان', nameFr: 'Relizane' },
    { nameAr: 'الحمادنة', nameFr: 'El H\'madna' },
    { nameAr: 'الرمكة', nameFr: 'Ramka' },
  ],
  49: [
    { nameAr: 'تنركوك', nameFr: 'Tinerkouk' },
    { nameAr: 'تيميمون', nameFr: 'Timimoun' },
    { nameAr: 'أولاد السعيد', nameFr: 'Ouled Said' },
    { nameAr: 'المطارفة', nameFr: 'Metarfa' },
    { nameAr: 'طالمين', nameFr: 'Talmine' },
    { nameAr: 'أولاد عيسى', nameFr: 'Ouled Aissa' },
    { nameAr: 'شروين', nameFr: 'Charouine' },
    { nameAr: 'أوقروت', nameFr: 'Aougrout' },
    { nameAr: 'دلدول', nameFr: 'Deldoul' },
    { nameAr: 'قصر قدور', nameFr: 'Ksar Kaddour' },
  ],
  50: [
    { nameAr: 'تيمياوين', nameFr: 'Timiaouine' },
    { nameAr: 'برج باجي مختار', nameFr: 'Bordj Badji Mokhtar' },
  ],
  51: [
    { nameAr: 'رأس الميعاد', nameFr: 'Ras El Miad' },
    { nameAr: 'بسباس', nameFr: 'Besbes' },
    { nameAr: 'سيدي  خالد', nameFr: 'Sidi Khaled' },
    { nameAr: 'الدوسن', nameFr: 'Doucen' },
    { nameAr: 'الشعيبة', nameFr: 'Chaiba' },
    { nameAr: 'أولاد جلال', nameFr: 'Ouled Djellal' },
  ],
  52: [
    { nameAr: 'بني عباس', nameFr: 'Beni-Abbes' },
    { nameAr: 'تامترت', nameFr: 'Tamtert' },
    { nameAr: 'إقلي', nameFr: 'Igli' },
    { nameAr: 'الواتة', nameFr: 'El Ouata' },
    { nameAr: 'أولاد خضير', nameFr: 'Ouled-Khodeir' },
    { nameAr: 'كرزاز', nameFr: 'Kerzaz' },
    { nameAr: 'تيمودي', nameFr: 'Timoudi' },
    { nameAr: 'القصابي', nameFr: 'Ksabi' },
    { nameAr: 'بن يخلف', nameFr: 'Beni-Ikhlef' },
  ],
  53: [
    { nameAr: 'إينغر', nameFr: 'Inghar' },
    { nameAr: 'عين صالح', nameFr: 'Ain Salah' },
    { nameAr: 'فقارة الزوى', nameFr: 'Foggaret Ezzoua' },
  ],
  54: [
    { nameAr: 'تين زواتين', nameFr: 'Tin Zouatine' },
    { nameAr: 'عين قزام', nameFr: 'Ain Guezzam' },
  ],
  55: [
    { nameAr: 'تماسين', nameFr: 'Temacine' },
    { nameAr: 'سيدي سليمان', nameFr: 'Sidi Slimane' },
    { nameAr: 'المقارين', nameFr: 'Megarine' },
    { nameAr: 'النزلة', nameFr: 'Nezla' },
    { nameAr: 'بلدة اعمر', nameFr: 'Blidet Amor' },
    { nameAr: 'تبسبست', nameFr: 'Tebesbest' },
    { nameAr: 'تقرت', nameFr: 'Touggourt' },
    { nameAr: 'الطيبات', nameFr: 'Taibet' },
    { nameAr: 'العالية', nameFr: 'El Alia' },
    { nameAr: 'الحجيرة', nameFr: 'El-Hadjira' },
    { nameAr: 'بن ناصر', nameFr: 'Benaceur' },
    { nameAr: 'المنقر', nameFr: 'M\'naguer' },
    { nameAr: 'الزاوية العابدية', nameFr: 'Zaouia El Abidia' },
  ],
  56: [
    { nameAr: 'جانت', nameFr: 'Djanet' },
    { nameAr: 'برج الحواس', nameFr: 'Bordj El Haouass' },
  ],
  57: [
    { nameAr: 'أم الطيور', nameFr: 'Oum Touyour' },
    { nameAr: 'سيدي عمران', nameFr: 'Sidi Amrane' },
    { nameAr: 'المرارة', nameFr: 'M\'rara' },
    { nameAr: 'جامعة', nameFr: 'Djamaa' },
    { nameAr: 'تندلة', nameFr: 'Tenedla' },
    { nameAr: 'المغير', nameFr: 'El-M\'ghaier' },
    { nameAr: 'سطيل', nameFr: 'Still' },
    { nameAr: 'سيدي خليل', nameFr: 'Sidi Khelil' },
  ],
  58: [
    { nameAr: 'المنيعة', nameFr: 'El Meniaa' },
    { nameAr: 'حاسي القارة', nameFr: 'Hassi Gara' },
    { nameAr: 'حاسي الفحل', nameFr: 'Hassi Fehal' },
  ],
};
